### ISSUE TITLE
mlsql 1.3.0 load mongodb return empty list

### ISSUE THREAD

**Issue by zhangsancode** [byzer-org/byzer-lang#1055]
I can save data to mongodb success, but when i load mongo select data, It response empty list

`        
set data='''
{"jack":"hello world sky2222"}
''';

load jsonStr.`data` as data1;
    
    save overwrite data1 as mongo.`answer/cool` where
    partitioner="MongoPaginateBySizePartitioner"
    -- and implClass="com.mongodb.spark.sql.DefaultSource"
    and uri="mongodb://root:password@ip:port/admin"
    and spark.mongodb.output.database="answer"
    and spark.mongodb.output.collection="cool";
`

i look my mongodb, it have data

`
    load mongo.`answer/cool` where
    partitioner="MongoPaginateBySizePartitioner"
    -- and implClass="com.mongodb.spark.sql.DefaultSource"
    and uri="mongodb://root:password@ip:port/admin"
    and spark.mongodb.input.database='answer'
    and spark.mongodb.input.collection='cool'
    as table1;
    
    select * from table1 as output1;
`
it response empty list  []

the run log 
19/05/10 15:37:08 INFO memory.MemoryStore: Block broadcast_91 stored as values in memory (estimated size 304.0 B, free 912.2 MB)
19/05/10 15:37:08 INFO memory.MemoryStore: Block broadcast_91_piece0 stored as bytes in memory (estimated size 194.0 B, free 912.2 MB)
19/05/10 15:37:08 INFO storage.BlockManagerInfo: Added broadcast_91_piece0 in memory on 10.222.95.176:45938 (size: 194.0 B, free: 912.3 MB)
19/05/10 15:37:08 INFO spark.SparkContext: Created broadcast 91 from broadcast at MongoSpark.scala:542
19/05/10 15:37:08 INFO driver.cluster: Cluster created with settings {hosts=[s-2ze35a049873b474.mongodb.rds.aliyuncs.com:3717], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
19/05/10 15:37:08 INFO driver.cluster: Cluster description not yet available. Waiting for 30000 ms before timing out
19/05/10 15:37:08 INFO driver.connection: Opened connection [connectionId{localValue:60}] to s-2ze35a049873b474.mongodb.rds.aliyuncs.com:3717
19/05/10 15:37:08 INFO driver.cluster: Monitor thread successfully connected to server with description ServerDescription{address=s-2ze35a049873b474.mongodb.rds.aliyuncs.com:3717, type=SHARD_ROUTER, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 0]}, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=744897}
19/05/10 15:37:08 INFO connection.MongoClientCache: Creating MongoClient: [s-2ze35a049873b474.mongodb.rds.aliyuncs.com:3717]
19/05/10 15:37:08 INFO driver.connection: Opened connection [connectionId{localValue:61}] to s-2ze35a049873b474.mongodb.rds.aliyuncs.com:3717
19/05/10 15:37:08 INFO spark.SparkContext: Starting job: treeAggregate at MongoInferSchema.scala:88
19/05/10 15:37:08 INFO scheduler.DAGScheduler: Got job 48 (treeAggregate at MongoInferSchema.scala:88) with 1 output partitions
19/05/10 15:37:08 INFO scheduler.DAGScheduler: Final stage: ResultStage 64 (treeAggregate at MongoInferSchema.scala:88)
19/05/10 15:37:08 INFO scheduler.DAGScheduler: Parents of final stage: List()
19/05/10 15:37:08 INFO scheduler.DAGScheduler: Missing parents: List()
19/05/10 15:37:08 INFO scheduler.DAGScheduler: Submitting ResultStage 64 (MapPartitionsRDD[374] at treeAggregate at MongoInferSchema.scala:88), which has no missing parents
19/05/10 15:37:08 INFO memory.MemoryStore: Block broadcast_92 stored as values in memory (estimated size 6.1 KB, free 912.2 MB)
19/05/10 15:37:08 INFO memory.MemoryStore: Block broadcast_92_piece0 stored as bytes in memory (estimated size 3.2 KB, free 912.2 MB)
19/05/10 15:37:08 INFO storage.BlockManagerInfo: Added broadcast_92_piece0 in memory on 10.222.95.176:45938 (size: 3.2 KB, free: 912.3 MB)
19/05/10 15:37:08 INFO spark.SparkContext: Created broadcast 92 from broadcast at DAGScheduler.scala:1006
19/05/10 15:37:08 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 64 (MapPartitionsRDD[374] at treeAggregate at MongoInferSchema.scala:88) (first 15 tasks are for partitions Vector(0))
19/05/10 15:37:08 INFO cluster.YarnScheduler: Adding task set 64.0 with 1 tasks
19/05/10 15:37:08 INFO scheduler.FairSchedulableBuilder: Added task set TaskSet_64.0 tasks to pool default
19/05/10 15:37:08 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 64.0 (TID 71, ryze-1.bigdata.com, executor 12, partition 0, RACK_LOCAL, 5006 bytes)
19/05/10 15:37:08 INFO storage.BlockManagerInfo: Added broadcast_92_piece0 in memory on ryze-1.bigdata.com:40834 (size: 3.2 KB, free: 912.3 MB)
19/05/10 15:37:08 INFO storage.BlockManagerInfo: Added broadcast_91_piece0 in memory on ryze-1.bigdata.com:40834 (size: 194.0 B, free: 912.3 MB)
19/05/10 15:37:09 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 64.0 (TID 71) in 96 ms on ryze-1.bigdata.com (executor 12) (1/1)
19/05/10 15:37:09 INFO cluster.YarnScheduler: Removed TaskSet 64.0, whose tasks have all completed, from pool default
19/05/10 15:37:09 INFO scheduler.DAGScheduler: ResultStage 64 (treeAggregate at MongoInferSchema.scala:88) finished in 0.096 s
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Job 48 finished: treeAggregate at MongoInferSchema.scala:88, took 0.104449 s
19/05/10 15:37:09 INFO execution.SparkSqlParser: Parsing command: table1
19/05/10 15:37:09 INFO execution.SparkSqlParser: Parsing command: select * from table1
19/05/10 15:37:09 INFO execution.SparkSqlParser: Parsing command: output1
19/05/10 15:37:09 INFO execution.SparkSqlParser: Parsing command: select * from output1 limit 5000
19/05/10 15:37:09 INFO partitioner.MongoPaginateBySizePartitioner: Could not find collection ('cool'), using a single partition
19/05/10 15:37:09 INFO spark.SparkContext: Starting job: collect at RestController.scala:161
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Registering RDD 380 (toJSON at RestController.scala:161)
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Got job 49 (collect at RestController.scala:161) with 1 output partitions
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Final stage: ResultStage 66 (collect at RestController.scala:161)
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Parents of final stage: List(ShuffleMapStage 65)
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Missing parents: List(ShuffleMapStage 65)
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Submitting ShuffleMapStage 65 (MapPartitionsRDD[380] at toJSON at RestController.scala:161), which has no missing parents
19/05/10 15:37:09 INFO memory.MemoryStore: Block broadcast_93 stored as values in memory (estimated size 10.5 KB, free 912.2 MB)
19/05/10 15:37:09 INFO memory.MemoryStore: Block broadcast_93_piece0 stored as bytes in memory (estimated size 5.6 KB, free 912.1 MB)
19/05/10 15:37:09 INFO storage.BlockManagerInfo: Added broadcast_93_piece0 in memory on 10.222.95.176:45938 (size: 5.6 KB, free: 912.2 MB)
19/05/10 15:37:09 INFO spark.SparkContext: Created broadcast 93 from broadcast at DAGScheduler.scala:1006
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ShuffleMapStage 65 (MapPartitionsRDD[380] at toJSON at RestController.scala:161) (first 15 tasks are for partitions Vector(0))
19/05/10 15:37:09 INFO cluster.YarnScheduler: Adding task set 65.0 with 1 tasks
19/05/10 15:37:09 INFO scheduler.FairSchedulableBuilder: Added task set TaskSet_65.0 tasks to pool default
19/05/10 15:37:09 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 65.0 (TID 72, ryze-1.bigdata.com, executor 12, partition 0, RACK_LOCAL, 4995 bytes)
19/05/10 15:37:09 INFO storage.BlockManagerInfo: Added broadcast_93_piece0 in memory on ryze-1.bigdata.com:40834 (size: 5.6 KB, free: 912.3 MB)
19/05/10 15:37:09 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 65.0 (TID 72) in 25 ms on ryze-1.bigdata.com (executor 12) (1/1)
19/05/10 15:37:09 INFO cluster.YarnScheduler: Removed TaskSet 65.0, whose tasks have all completed, from pool default
19/05/10 15:37:09 INFO scheduler.DAGScheduler: ShuffleMapStage 65 (toJSON at RestController.scala:161) finished in 0.025 s
19/05/10 15:37:09 INFO scheduler.DAGScheduler: looking for newly runnable stages
19/05/10 15:37:09 INFO scheduler.DAGScheduler: running: Set()
19/05/10 15:37:09 INFO scheduler.DAGScheduler: waiting: Set(ResultStage 66)
19/05/10 15:37:09 INFO scheduler.DAGScheduler: failed: Set()
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Submitting ResultStage 66 (MapPartitionsRDD[386] at collect at RestController.scala:161), which has no missing parents
19/05/10 15:37:09 INFO memory.MemoryStore: Block broadcast_94 stored as values in memory (estimated size 13.2 KB, free 912.1 MB)
19/05/10 15:37:09 INFO memory.MemoryStore: Block broadcast_94_piece0 stored as bytes in memory (estimated size 6.6 KB, free 912.1 MB)
19/05/10 15:37:09 INFO storage.BlockManagerInfo: Added broadcast_94_piece0 in memory on 10.222.95.176:45938 (size: 6.6 KB, free: 912.2 MB)
19/05/10 15:37:09 INFO spark.SparkContext: Created broadcast 94 from broadcast at DAGScheduler.scala:1006
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 66 (MapPartitionsRDD[386] at collect at RestController.scala:161) (first 15 tasks are for partitions Vector(0))
19/05/10 15:37:09 INFO cluster.YarnScheduler: Adding task set 66.0 with 1 tasks
19/05/10 15:37:09 INFO scheduler.FairSchedulableBuilder: Added task set TaskSet_66.0 tasks to pool default
19/05/10 15:37:09 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 66.0 (TID 73, ryze-1.bigdata.com, executor 12, partition 0, PROCESS_LOCAL, 4738 bytes)
19/05/10 15:37:09 INFO storage.BlockManagerInfo: Added broadcast_94_piece0 in memory on ryze-1.bigdata.com:40834 (size: 6.6 KB, free: 912.3 MB)
19/05/10 15:37:09 INFO spark.MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 16 to 10.222.95.178:43324
19/05/10 15:37:09 INFO spark.MapOutputTrackerMaster: Size of output statuses for shuffle 16 is 150 bytes
19/05/10 15:37:09 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 66.0 (TID 73) in 22 ms on ryze-1.bigdata.com (executor 12) (1/1)
19/05/10 15:37:09 INFO cluster.YarnScheduler: Removed TaskSet 66.0, whose tasks have all completed, from pool default
19/05/10 15:37:09 INFO scheduler.DAGScheduler: ResultStage 66 (collect at RestController.scala:161) finished in 0.022 s
19/05/10 15:37:09 INFO scheduler.DAGScheduler: Job 49 finished: collect at RestController.scala:161, took 0.062751 s
19/05/10 15:37:09 INFO processor.impl: Completed 200 in 284ms 	POST /run/script

**Comment by allwefantasy** [comment]
The URL format is wrong. Try change admin in `mongodb://root:password@ip:port/admin`  to your mongodb collection.

**Comment by latincross** [comment]
The implementation of mlsql is somewhat different from spark native support, and you can refer to this implementation.
https://github.com/allwefantasy/streamingpro/blob/master/streamingpro-mlsql/src/test/scala/streaming/test/datasource/MongoSpec.scala

**Comment by zhangsancode** [comment]
My mongo server is in Aliyun, it need auth user auth in admin db

**Comment by latincross** [comment]
I review some code,it's not a URL problem.

Change
and spark.mongodb.input.database='answer'
and spark.mongodb.input.collection='cool'
to
and spark.mongodb.input.database="answer"
and spark.mongodb.input.collection="cool"

it works.
