### ISSUE TITLE
mvn package fail

### ISSUE THREAD

**Issue by q1007239205** [byzer-org/byzer-lang#1078]
[ERROR] /MLSQLDFParser.scala:60: error: value name is not a member of org.apache.spark.sql.catalyst.plans.logical.SubqueryAlias
[INFO]         case wowlp: SubqueryAlias if wowlp.child.isInstanceOf[SubqueryAlias] && r.contains(wowlp.child.asInstanceOf[SubqueryAlias].name.unquotedString) => {

[ERROR]MLSQLDFParser.scala:61: error: value name is not a member of org.apache.spark.sql.catalyst.plans.logical.SubqueryAlias
[INFO]           val tableName = wowlp.name.unquotedString

**Comment by allwefantasy** [comment]
Please try again with the master branch. Notice that in 1.3.0-SNAPSHOT we will not support spark 2.2.x again. For now, we support 2.3.2/2.4.3. Make sure you compile with package.sh script.
