### ISSUE TITLE
Apply for using  with try.mlsql.tech 

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/byzer-lang#1100]
-- 
-- Step 1:
--       Register you owner account, 
-- Step 2:
--       Leave you account name in https://github.com/allwefantasy/streamingpro/issues/1100. 
-- Step 3:
--       We will invite you to the demo team, and once we done, we will notice you in Issue-1100
-- Step 4:
--      You should accept the invitation in `Team/Team/Team inviting you`
--      Notice us inIssue-1100.
-- Step 5:
--      Configure backend for your account. We will comment in inIssue-1100.
-- Step 6: 
--      You should set default backend in `Team/Cluster/Set default backend`

-- Done

**Comment by zhangabel** [comment]
麻烦帮我拉进 demo team 谢谢！
账户：zlhuan@gmail.com

**Comment by allwefantasy** [comment]
Try this：
```
account:  demo@gmail.com
password: 123456
```
