### ISSUE TITLE
How to show hive databases or tables on MLSQL console

### ISSUE THREAD

**Issue by lordk911** [byzer-org/byzer-lang#1136]
How to show hive databases or tables on MLSQL console ?
I can load a hive table , but if I just want to see what databases or what a database contains what tables , I don't know how to spell the mlsql.

**Comment by latincross** [comment]
!show tables;
!show tables named view_table;
!show tables from database(your database name);
!show tables from database named view_table;

**Comment by lordk911** [comment]
thanks, I tried  !show tables;
the error log from console is:
------------------------------------------------------------------------------
backend status:500

path [tables] is not found. please check the doc website for more details:
http://docs.mlsql.tech/zh
------------------------------------------------------------------------------
And if I try: load hive.`hdm.wms_orders` as table1; 
console will take 5 thousand rows to display , but the console also show some errors: 
------------------------------------------------------------------------------
backend status:500
No response from backend. Make sure all engines configured properly
[]
backend status:500
No response from backend. Make sure all engines configured properly
backend status:500
No response from backend. Make sure all engines configured properly
backend status:500
No response from backend. Make sure all engines configured properly

Time cost:22407ms
backend status:500
No response from backend. Make sure all engines configured properly
[]
------------------------------------------------------------------------------

**Comment by latincross** [comment]
This Method is in the master branch and will be available in the next public version.You can compile the master branch.

**Comment by lordk911** [comment]
OK, Thanks.

**Comment by latincross** [comment]
Console for testing, will limit the number of return datas, prevent driver oom, you can call the rest interface, pass the parameter outputSize to control the number of output datas. 
Like this:
curl -X POST "http://127.0.0.1:9003/run/script?" -d '
defaultPathPrefix=/tmp&owner=admin&sql=!hdfs -ls -F /;&outputSize=4'
