### ISSUE TITLE
Missing function that automatically infer the schema of complex json fields

### ISSUE THREAD

**Issue by weicm** [byzer-org/byzer-lang#1151]
For example, we loaded a table with a complex json field of type string. 
We want to expand the contents of this field. The function from_json that spark comes with needs to manually fill the shema. 
This is very difficult when json is very complicated. 
So we need a function that automatically infer the shema.

**Comment by allwefantasy** [comment]
We will add a tool to help people infer json field schema in release 1.4.0 or 1.3.x.
