### ISSUE TITLE
使用docker按照MLSQL，无法注册，登录

### ISSUE THREAD

**Issue by hsh8523** [byzer-org/byzer-lang#1178]
使用email:aa@fybdp.com 注册，提示：“org.hibernate.exception.SQLGrammarException: could not extract ResultSet”

**Comment by allwefantasy** [comment]
是1.4.0-SNAPSHOT版本么？还是1.3.0版本的docker?

**Comment by allwefantasy** [comment]
已经修正。数据库脚本没有更新。
