### ISSUE TITLE
ML SQL design

### ISSUE THREAD

**Issue by datafibers** [byzer-org/byzer-lang#119]
A quick question regarding the design of MLSQL. 
Does MLSQL parsed predefined SQL keywords, such as train, to generate scala or python code running against Spark MLLib?

**Comment by allwefantasy** [comment]
We create a new DSL layer which will translate some query eg. `train`,` select`, or `register`  to real SQL or MLlib function call.  We do not generate Scala or Python code dynamically at runtime, just call existed functions. 
When training tensorflow we will fork python process and invoke tensorflow python script, for now, we just only support tensorflow distributed hyperparameter tunning.
