### ISSUE TITLE
有两个问题问下

### ISSUE THREAD

**Issue by zheniantoushipashi** [byzer-org/byzer-lang#12]
1  后续提pr, 要 新建feature  branch 提到 develop么， 之前看错提到 master了，你给merge了

2  对新加的一个正则 RegexParserCompositor 写了文档不知道放在哪个目录中提交。

**Comment by allwefantasy** [comment]
Q: 后续提pr, 要 新建feature branch 提到 develop么， 之前看错提到 master了，你给merge了

不需要。你现在已经fork了一份，然后你可以自己新建一个分支。测试通过了就可以合并到你的master分支上。然后再提交PR。和现在的模式一样。

Q :  对新加的一个正则 RegexParserCompositor 写了文档不知道放在哪个目录中提交。

不知道Wiki权限是不是默认开放。你可以在doc目录写一份。然后我帮你放到wiki中。最好是Markdown的。
