### ISSUE TITLE
无法编译成功

### ISSUE THREAD

**Issue by lstq-lab** [byzer-org/byzer-lang#120]
![image](https://user-images.githubusercontent.com/31727374/35729252-0b8aa5ac-0849-11e8-82e3-9cbec3f84bf2.png)

**Comment by allwefantasy** [comment]
这么奇怪。 你maven 版本是多少。我一般使用 maven 3.3.9。 你可以尝试下。

**Comment by allwefantasy** [comment]
另外 最好是有VPN。

**Comment by Tom-YJ** [comment]
请问楼主解决了吗？我使用maven3.3.9有VPN，编译也出现相同的问题。 @flydish2017 @allwefantasy

**Comment by cfmcgrady** [comment]
@Tom-YJ @flydish2017 
- 1. 删除maven本地缓存
```
rm -rf $HOME/.m2
```
- 2. 拉取最新代码，重新打包即可

**Comment by allwefantasy** [comment]
@cfmcgrady 赞👍

**Comment by allwefantasy** [comment]
另外，如果还是这个错误，不妨手动把自己的settings改成阿里云的。

**Comment by Tom-YJ** [comment]
好的，谢谢

**Comment by robin-su** [comment]
您好，我通过idea编译了streamingpro，并成功在部署，但是我发现当我发送http请求时，报这个错误：
![default](https://user-images.githubusercontent.com/19170760/39682657-d4148da6-51e3-11e8-8521-e3301ee9f5a1.png)

**Comment by robin-su** [comment]
如果kafka中的数据类型是{“a”:"1","b":"2","c":"3","d":"4"可以支持注册成表吗?

**Comment by robin-su** [comment]
如果kafka中的数据类型是{“a”:"1","b":"2","c":"3","d":"4"}可以支持注册成表吗?

**Comment by robin-su** [comment]
大神您好：我还是没搞明白，您看我的json串是：
{
  "you-first-streaming-job": {
    "desc": "just a example",
    "strategy": "streaming.core.strategy.SparkStreamingStrategy",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "stream.sources",
        "params": [
          {
            "format": "kafka",
            "bootstrap.servers": "xxx.xxx.xxx:9092",
            "topics": "dataGenerator3",
            "auto.offset.reset": "smallest",
            "path": "-"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.streaming.transformation.SingleColumnJSONCompositor",
        "params": [
          {
            "name": "a"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.streaming.transformation.JSONTableCompositor",
        "params": [
          {
            "tableName": "kafkatest"
          }
        ]
      },
      {
        "name": "stream.outputs",
        "params": [
          {
            "name": "jack",
            "format": "console",
            "path": "-",
            "inputTableName": "kafkatest",
            "mode": "Overwrite"
          }
        ]
      }
    ],
    "configParams": {}
  }
}

但是他却报：

![34b0ln o9 g7ph du_9sl](https://user-images.githubusercontent.com/19170760/39743882-f97d690e-52d4-11e8-9e9c-da56b1d2404b.png)
streaming.core.compositor.spark.streaming.transformation.SingleColumnJSONCompositor
这个类找不到，但是我看了源码，这个类位于：streamingpro-spark这个子工程下，而不是streamingpro-spark-2.0，请问大神这个问题该怎么解决呢？

**Comment by allwefantasy** [comment]
这个不影响，这个是浏览器都会清酒一个favincon.ico文件，方便在浏览器tab上显示。

**Comment by wodo2008** [comment]
请问这个错误是什么原因导致的呢？
![1528211416989](https://user-images.githubusercontent.com/12986007/40985065-da449cd6-6915-11e8-8802-86c73acc3d4c.jpg)

**Comment by justAAbug** [comment]
![image](https://user-images.githubusercontent.com/40822378/42266220-590c8af8-7fa8-11e8-90e1-4ec82983b5b4.png)
我用的CDH5.10.2    JDK 1.8   scala 2.11   spark 2.2.0  安装文档上说的启动怎么会有这个错误，是哪里的冲突

**Comment by SKY-Hao** [comment]
![image](https://user-images.githubusercontent.com/31984778/51423775-ef7bf700-1bff-11e9-9e01-bcd52a1c7278.png)
您好我使用的IDEA mvn install 报错
