### ISSUE TITLE
'failOnDataLoss' config not work when process kafka data

### ISSUE THREAD

**Issue by lordk911** [byzer-org/byzer-lang#1242]
ERROR :
backend status:500
Job aborted due to stage failure: Task 1 in stage 0.0 failed 4 times, most recent failure: Lost task 1.3 in stage 0.0 (TID 9, bdp-scm-03, executor 1): java.lang.IllegalStateException: Cannot fetch offset 13 (GroupId: spark-kafka-relation-4f1952ac-155b-496a-9612-82cdbd934553-executor, TopicPartition: test2-1). 
Some data may have been lost because they are not available in Kafka any more; either the
 data was aged out by Kafka or the topic may have been deleted before all the data in the
 topic was processed. If you don't want your streaming query to fail on such cases, set the
 source option "failOnDataLoss" to "false".

MY CODE IS : 

!kafkaTool registerSchema 2 records from "bdp-docker-01:9092" test2;
-- convert table as stream source
load kafka.`test2` options 
kafka.bootstrap.servers="bdp-docker-01:9092"
and failOnDataLoss = "false"
as newkafkatable1;

**Comment by allwefantasy** [comment]
This is may caused by the `!kafkaTool` comamnd instead of the load kafka. We will set failOnDataLoss true as default in `!kafkaTool`.

**Comment by lordk911** [comment]
ok,thanks.
