### ISSUE TITLE
关于mongo数据源

### ISSUE THREAD

**Issue by Mryandada** [byzer-org/byzer-lang#1268]
在配置mongo数据源的时候，找对jar包是件非常重要的事情，请注意仔细核对mongo数据库驱动包的版本

**Comment by Mryandada** [comment]
接下来，我觉得可以完善一下，操作手册中的内容，扩展一下oracle数据源的连接方式

**Comment by allwefantasy** [comment]
可以将MongoDB做成一个插件。参考 https://github.com/allwefantasy/mlsql-pluins/tree/master/ds-hbase-2x
