### ISSUE TITLE
CURD problem

### ISSUE THREAD

**Issue by ww102111** [byzer-org/byzer-lang#13]
自己使用curl尝试添加一个新的任务时候，
curl: (7) Failed to connect to 10.108.166.96 port 9902: Connection refused

**Comment by allwefantasy** [comment]
启动的时候指定了端口么？-streaming.driver.port 9004

**Comment by ww102111** [comment]
指定的9003 -streaming.driver.port 9003

**Comment by allwefantasy** [comment]
那么你要访问的端口应该是 9003  你通过curl 明显访问的是9902?

**Comment by DoctorQ** [comment]
-streaming.driver.port指定的端口号，通过curl访问的时候端口要一样。可能看到作者wiki的一个例子写的9902，所以疑惑了。

**Comment by ww102111** [comment]
哦哦，也对哈，我试试9002的。

**Comment by ww102111** [comment]
可以联系上，一个aplication是对应一个sparkcontext的。如何curl post传过去的时候，如何保证把这个job添加上去，是必须要用yarn集群模式的吗。这样动态添加成功的话，那个 /runtime/stop，这个时候是停止的所有的application吧。

**Comment by allwefantasy** [comment]
本质上是停掉整个Context,然后再启动。以流式计算为例，Spark 是不允许动态添加job的。

**Comment by ww102111** [comment]
那想问一下这个动态添加job最后的效果是啥哈，我试了试post 到job上，在spark的job ui上面是没有显示添加成功的。

**Comment by allwefantasy** [comment]
动态添加job仅限于spark streaming。 比如，在配置文件里，你可以配置多个数据流，正常情况你可能配置的是一个，现在你想再添加一个，就可以通过post job的方式。这两个你可以放在一个spark streaming进程中，也可以其多个spark streaming.目前来说，受限于spark streaming自身的要求，我们建议一个job 一个spark streaming实例比较合适，这样比较适合生产环境。

**Comment by ww102111** [comment]
嗯嗯，我就用spark streaming配置数据流。后来开启了streaming的job后，再post Job一个新的job，在一个进程里面没有显示这个添加的job成功执行，反正在worker:4040 UI中没有显示。

**Comment by allwefantasy** [comment]
了解了。那就不用这个功能。这个功能有点宣传性质，因为底层Spark不支持添加新的数据流处理流。

StreamingPro具体的做法是：

是先停掉已有的StreamingContext,然后重新新建一个新的，新的会读取保存在HDFS上的Kafka的偏移量继续进行消费。
