### ISSUE TITLE
MLSQL默认是跑在社区版上的，如果要跑到CDH该怎么办？

### ISSUE THREAD

**Issue by anan0120** [byzer-org/byzer-lang#1317]
1、将cdh上对应的core-site.xml、hdfs-site.xml、hive-site.xml、yarn-site.xml 传到spark社区版的conf目录
2、修改engine的启动脚本
   --master local[*]  修改为：--master yarn-client
   
   增加三个参数设置：不设置会出现任务集中到1台机器上
    --num-executors 50 \
    --executor-memory 4G \
    --executor-cores 2 \   --具体设置请根据集群情况设置，怎么设置才能发挥更大的效果
    
    
    --master local[*]  修改为：--master yarn-cluster --此种办法，不推荐，因为这个提交后，会随意分发机器

如果有报错 Cannot run program "/etc/hadoop/conf.cloudera.yarn/topology.py 没有那个文件或目录  将core_site.xml中配置注销掉

**Comment by allwefantasy** [comment]
可以加一些背景解释。比如MLSQL默认是跑在社区版上的，如果要跑到CDH该怎么办。
另外 --master yarn-client 应该是比较合理的使用方式。

**Comment by anan0120** [comment]
已修正
