### ISSUE TITLE
自定义脚本context方式能在集群执行吗？

### ISSUE THREAD

**Issue by WinterW** [byzer-org/byzer-lang#1340]
脚本里如果使用了map算子，集群模式下会出现错误
```cannot assign instance of scala.collection.immutable.List$SerializationProxy to field org.apache.spark.rdd.RDD.org$apache$spark$rdd$RDD$$dependencies_ of type scala.collection.Seq in instance of org.apache.spark.rdd.MapPartitionsRDD```

下面代码在zeppelin里可以执行，自定义脚本执行会出现上面的错误
```
import context.implicits._

val df = context.table("t_sample_pos")

val graphData = df.flatMap(x=> {

    val clickItemList = x.getSeq[String](1)

    clickItemList.sliding(2, 1)

}).map(x => x.mkString(" ")).toDF("data")

graphData.show(5)
```
跟下面链接的错误有点像，spark版本2.3
https://issues.apache.org/jira/browse/SPARK-9219
https://issues.apache.org/jira/browse/SPARK-24728

**Comment by allwefantasy** [comment]
能给出一个例子么？
