### ISSUE TITLE
[Engine][2.1.0][BUG]Jdbc Upsert JDBCOptions ClassCastException

### ISSUE THREAD

**Issue by wudj496** [byzer-org/byzer-lang#1394]
mlsql version：2.1.0-SNASHOT
Spark version: 3.0.1

问题描述：jdbc upsert时发生classcast异常

原因：spark3.0.1把DataFrameWriter的extraOptions由scala.collection.mutable.HashMap改成CaseInsensitiveMap导致的

**Comment by allwefantasy** [comment]
在最新的 2.1.0-SNAPSHOT中已经修复。
