### ISSUE TITLE
任务(6)： 高阶机器学习-从训练到预测

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/byzer-lang#1409]
MLSQL 高阶机器学习特点:

1. 基本无需编码，使用已有特征库，机器学习库
2. MLSQL分布式引擎可以做离线训练，批量预测，流式预测
3. MLSQL单机引擎可以做API服务

根据文档 [RandomForest](http://docs.mlsql.tech/mlsql-stack/algs/random_forest.html)，

1. 训练得到一个模型路径
2. 在同一引擎上完成批量预测

根据文档[部署算法API服务](http://docs.mlsql.tech/mlsql-stack/api_deploy/),了解MLSQL 预测服务部署原理，并根据[部署步骤](http://docs.mlsql.tech/mlsql-stack/api_deploy/case.html)将我们上面得到的模型注册到该预测服务上，使用Http接口完成模型预测。

**Comment by lwz9103** [comment]
https://lwz9103.github.io/2021/03/22/mlsql-task-6/

**Comment by Mukvin** [comment]
作业：
https://mukvin.com/MLSQL-env-Machine-Learning-9c7453170f2d442bb33f7380f35f2a79
