### ISSUE TITLE
Z-Ordering当indexFields指定的字段值是空抛异常问题

### ISSUE THREAD

**Issue by ryan-0526** [byzer-org/byzer-lang#1430]
mlsql version：mlsql-engine_2.4-2.1.0

问题描述：

* 在使用train向原表中增加索引列时，如果indexFields中指定的字段值有空值，抛出空指针异常
            train castTable as ZOrdering.`` 
            where indexFields = "ID,FILEID,OBJECTNUM"
            and fileNum="10"
            as newDF;

*抛出：

            caused by：
            java.lang.NullPointerException
            tech.mlsql.tool.ZOrderingBytesUtil.utf8To8Byte(ZOrderingBytesUtil.java:115)
            tech.mlsql.indexer.impl.ZOrderingIndexer$$anonfun$18$$anonfun$19.apply(ZOrderingIndexer.scala:202)
            tech.mlsql.indexer.impl.ZOrderingIndexer$$anonfun$18$$anonfun$19.apply(ZOrderingIndexer.scala:191)
            scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
            scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
            scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
            scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
            scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
            scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)

**Comment by allwefantasy** [comment]
已解决。参看： https://github.com/allwefantasy/mlsql/pull/1438
