### ISSUE TITLE
交互式Python 异常

### ISSUE THREAD

**Issue by hecheng64** [byzer-org/byzer-lang#1455]
脚本如下：部署是mlsql-engine_2.4-2.0.0
!python start;
!python env "PYTHON_ENV=source /root/miniconda3/bin/activate dev";
!python conf "schema=st(field(a,integer),field(b,integer))";
!python  '''
import pandas as pd
import numpy as np
df = pd.DataFrame({'AAA': [4, 5, 6, 8],'BBB': [10, 20, 30, 40],'CCC': [100, 50, -30, -50]})
data_manager.set_output([[df['AAA'],df['BBB']]])
''';

报错：
Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)
java.net.PlainSocketImpl.socketConnect(Native Method)
java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
java.net.Socket.connect(Socket.java:589)
java.net.Socket.connect(Socket.java:538)
java.net.Socket.<init>(Socket.java:434)
java.net.Socket.<init>(Socket.java:211)
tech.mlsql.ets.PythonCommand.request$1(PythonCommand.scala:138

大概是什么原因？

**Comment by hecheng64** [comment]
感觉需要!python  on 才可以执行，后面只能看下源码怎么回事

**Comment by allwefantasy** [comment]
这个功能是实验性质的，建议不要取用。因为我们发现它没啥太大价值；如果需要python支持，请使用功能!ray 那个模块。

**Comment by hecheng64** [comment]
感谢
