### ISSUE TITLE
[ET] support analyze ET in MLSQL

### ISSUE THREAD

**Issue by hellozepp** [byzer-org/byzer-lang#1497]
MLSQL 主要接口是/run/script， 我们支持参数 executeMode, 该参数控制 MLSQL 的执行模式。默认该参数的值为 query，表示进行MLSQL脚本的执行。 其实他还提供了第二个选项analyze，实现MLSQL语法的解析。但是 analyze 对 select 语句解析的比较粗糙，只有raw,sql,tableName 三个部分。在很多场景里面，我们其实需要解析出SQL中所有的表，而不仅仅是这条SQL中生成的表。

可能有场景需要用到select语句里的表，这个我们可以通过et 来完成。用户可以发起如下的语句：
```
run command as SyntaxAnalyzeExt.`` where sql='''
select a from table1 as output
''';
```
需要提供一个 ET 支持解析功能。

--------------------------------------------
`/run/script` is an important interface of MLSQL. We support the parameter `executeMode`, which controls the execution mode of MLSQL. The default value of the parameter is `query`, which means to execute the MLSQL script. It also provides the second option, analyze, to realize the analysis of MLSQL syntax. But analyze is relatively rough in the analysis of select statements, and only has three parts: raw, sql, and tableName. In many scenarios, we actually need to parse out all the tables in SQL, not just the tables generated in this SQL.

There may be some scenes that need to use the table in the select statement, we can do it through `ET`. The user can use the following statement:
```
run command as SyntaxAnalyzeExt. `` where sql='''
select a from table1 as output
''';
```
We need to provide an ET to support the analyze function.

**Comment by hellozepp** [comment]
Complete test SQL：
```
set rawText='''
{"id":1,"content":"MLSQL是一个好的语言","label":0.0},
{"id":2,"content":"Spark是一个好的语言","label":1.0}
{"id":3,"content":"MLSQL语言","label":0.0}
{"id":4,"content":"MLSQL是一个好的语言","label":0.0}
{"id":5,"content":"MLSQL是一个好的语言","label":1.0}
{"id":6,"content":"MLSQL是一个好的语言","label":0.0}
{"id":7,"content":"MLSQL是一个好的语言","label":0.0}
{"id":8,"content":"MLSQL是一个好的语言","label":1.0}
{"id":9,"content":"Spark好的语言","label":0.0}
{"id":10,"content":"MLSQL是一个好的语言","label":0.0}
''';

load jsonStr.`rawText` as table1;
run command as SyntaxAnalyzeExt.`` where sql='''
select a from table1 as output
''';
```

Expected results：
```
 Total jobs: 1 current job:1 job script:run command as SyntaxAnalyzeExt.`` where sql='''
select a from table1 as output
''' 
 [table1]
```

**Comment by hellozepp** [comment]
@allwefantasy PTAL

**Comment by allwefantasy** [comment]
Good Job!

Maybe the ET name called `ExtractTableFromSQL ` is more clear than `SyntaxAnalyzeExt `?  Or if we hope `SyntaxAnalyzeExt` contains a bunch of functions e.g. extracting tables from sql, table dependency , we can add new parameter in where statement. 

 For Example:

```sql
run command as SyntaxAnalyzeExt.`` where 
action="extractTables"
sql='''
select a from table1 as output
''';
```

**Comment by hellozepp** [comment]
@allwefantasy Yes, this modification is a bit rough. I need to add some conditional support in the `where` statement. 
Does table dependency mean the data source type?
