### ISSUE TITLE
net文件夹jar

### ISSUE THREAD

**Issue by ww102111** [byzer-org/byzer-lang#15]
您好，我想自己增加streamingpro的reduce等算子，可以把那个这个工程上的上的本地仓库的net文件夹上传一下不。因为编译项目提示就是缺少里面的jar包。谢谢了

**Comment by allwefantasy** [comment]
参考这个： https://github.com/allwefantasy/streamingpro/wiki/Build
因为是使用Maven编译，如果你不自己编译，可能依赖不完整。

另外能否提出你需要的算子的需求？

**Comment by ww102111** [comment]
我就是按照自己编译的，还看到以前csdn上一个人也是这样maven编译的，我自己的确编译到框架那，就提示说ServiceFrame这个依赖包得不到。自己想增加多点spark的collect,take，reduce这些计算子，把常用的几个都添加上。

**Comment by allwefantasy** [comment]
为啥不用SQL或者Script? ServiceFrame 你也需要自己编译。

**Comment by ww102111** [comment]
因为看中了spark streaming这部分比叫好的各种计算因子，可以各种搭配起来做的运算。有一个项目需要只用spark streaming来处理数据

**Comment by ww102111** [comment]
快编译好了，里面有些Pom生成的jar版本号不一致，改好了就过了。thx。我想再多增加些spark的算子，那个动态添加的job有限制吗，大神

**Comment by allwefantasy** [comment]
1. 多加些算子是没有问题的。
2. 动态添加job的讨论参考： https://github.com/allwefantasy/streamingpro/issues/13  建议还是不要使用。主要是spark streaming自己支持的不太好。
