### ISSUE TITLE
LocalBaseTestSuite fails to support plugin based on spark 3.1.1

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/byzer-lang#1513]
The code in LocalBaseTestSuite shows that we hard code the plugin.

```scala
trait LocalBaseTestSuite extends FunSuite with SparkOperationUtil with BeforeAndAfterAll {

  var runtime: SparkRuntime = _
  var runParams: Array[String] = Array()
  var testCaseDirPath: String = _
  var dataDirPath: String = _
  var home: String = _
  val user = "admin"
  var initialPlugins: Seq[String] = Seq("mlsql-assert-2.4")
  var originClassLoader = Thread.currentThread().getContextClassLoader
```

We can use `MLSQLVersion.version()` to get MLSQL Engine Version and then load the correct plugin.

**Comment by lwz9103** [comment]
MLSQLVersion.version() returns mlsql version, not contains spark version. We can add spark version and scala version in  version file and use profile to make it.

**Comment by lwz9103** [comment]
![image](https://user-images.githubusercontent.com/23639010/130408883-dc86be5b-4eac-4750-846e-9dd7ea8b6a23.png)

**Comment by allwefantasy** [comment]
https://github.com/allwefantasy/mlsql/pull/1515
