### ISSUE TITLE
flink 编译小问题

### ISSUE THREAD

**Issue by lstq-lab** [byzer-org/byzer-lang#167]
[ERROR]   The project streaming.king:streamingpro-flink:0.4.15-SNAPSHOT-1.2.0 (E:\src\streamingpro\streamingpro-flink\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for streaming.king:streamingpro-common:jar is missing. @ streaming.king:streamingpro-flink:0.4.15-SNAPSHOT-${flink.version}, E:\src\streamingpro\streamingpro-flink\pom.xml, line 16, column 17

版本不一致， flink1.2.0 但是streamingpro-common版本号是1.1.0

**Comment by allwefantasy** [comment]
flink不是重点支持的。只是为了展现StreamingPro对多平台的支持能力。

**Comment by allwefantasy** [comment]
目前更新了flink版本，支持最新的flink 1.4.2。 https://github.com/allwefantasy/streamingpro/pull/215
具体编译以及使用文档参看：

https://github.com/allwefantasy/streamingpro/blob/master/docs/flink.md
