### ISSUE TITLE
splitflatmap

### ISSUE THREAD

**Issue by ww102111** [byzer-org/byzer-lang#17]
比如真实的map为 map(func) ，自己也想实现为这个格式的，关键这个map的参数是一个func的函数参数
自己  def sep = {
    config[String]("separator", _configParams)
  }
这里得到seq类似的字符串，想传递到func，
最后编译有问题，有没有好的思路哈，求大神指导。还是这样本身做就是行不通的呢。

**Comment by ww102111** [comment]
改造map算子的时候，
  def sep = {
    config[String]("separator", _configParams)
  }
    val func = map
 val separator: String = sep.get
    val newDstream = dstream.map(line => func(separator)))
    List(newDstream.asInstanceOf[T])
这里面使用了一个map函数，外面还要再使用一次dstream的map呢
二，想改造map(func)，而func直接是配置文件的separator，试了好几种思路都没有成功

**Comment by allwefantasy** [comment]
能把错误贴出来么？

**Comment by ww102111** [comment]
16/11/15 23:15:34 INFO DAGScheduler: Job 0 finished: collect at Dispatcher.scala:34, took 1.200195 s
Exception in thread "main" net.sf.json.JSONException: Expected a ':' after a key at character 470 of {
  "testJoinTable":{
    "desc": "����",
    "strategy": "streaming.core.strategy.SparkStreamingStrategy",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {

**Comment by cfmcgrady** [comment]
确认下你的json格式是否正确。

**Comment by cfmcgrady** [comment]
确认下你的配置文件json格式是否正确

**Comment by ww102111** [comment]
嗯，"params": [{"separator":"",""}]这里面用一个双引号就对了，求教一下哈，想更好的改造一下算子类计算
比如 map(func) 这个工程实现了map(line=>(line,1))，自己想实现为map(func)。试了几次都失败了

**Comment by ww102111** [comment]
还有实现那个Union算子的话，有好的建议吗，比较union是合并两个dstream，
dstream也没有collect方法
