### ISSUE TITLE
同一配置文件中多个jobs初始化时的依赖问题

### ISSUE THREAD

**Issue by maxlubb** [byzer-org/byzer-lang#18]
##### 问题说明：
多个属于同一类业务的jobs放在一个配置文件中，且多个jobs彼此之间没有依赖关系，在执行其中一个job时，发现所有该配置文件中所有jobs都会被初始化。

所以，会有下面的顾虑：
**若某job配置或其他原因导致初始化失败时，会影响其他jobs的正常执行，并导致其他jobs执行失败**

**Comment by ww102111** [comment]
你是否试过把多个job放在不同的配置文件中，然后submit提交的时候，把所有Job都提交了呢

**Comment by allwefantasy** [comment]
应该已经使用了参数-streaming.jobs  选择具体要执行的Job吧？
