### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ww102111** [byzer-org/byzer-lang#19]
restController中：
 if (!runtime.isInstanceOf[SparkStreamingRuntime]) if前面需要加上！，望知晓。
另外要是启动的时候， set spark.driver.allowMultipleContexts = true的话，是不是性能就受很大影响了哈
但是这样是可以动态添加job的。

**Comment by allwefantasy** [comment]
恩 是有这个问题。我觉得你提的也是一个方案。不过我没有这么做过。
