### ISSUE TITLE
Error: SparkRuntime cannot be cast to SparkStreamingRuntime

### ISSUE THREAD

**Issue by ky1987** [byzer-org/byzer-lang#2]
when I am running 
_./bin/spark-submit   --class streaming.core.StreamingApp \
--master local[2] \
--name sql-interactive \
/tmp/streamingpro-0.2.1-SNAPSHOT-online-1.6.1.jar    \
-streaming.name sql-interactive    \
-streaming.platform spark   \
-streaming.rest true   \
-streaming.driver.port 9004   \
-streaming.spark.service true_

it is giving me Error:
_Exception in thread "main" java.lang.ClassCastException: streaming.core.strategy.platform.SparkRuntime cannot be cast to streaming.core.strategy.platform.SparkStreamingRuntime_

Any help would be appreciated.

Thanks

**Comment by allwefantasy** [comment]
Fixed in new version.  

Preview build Package(newest version please check README in project):

> spark 1.6.1   http://pan.baidu.com/s/1pKWOSqR password: e5q9
> spark 1.5.1   http://pan.baidu.com/s/1i5g46od password: h4n8
