### ISSUE TITLE
MockInputStreamCompositor，MockJsonCompositor，JSONTableCompositor 包缺少

### ISSUE THREAD

**Issue by jinky2004** [byzer-org/byzer-lang#200]
运行文档给的例子， 报包缺失， 目前看以spark-2.2.0 方式编译出来的包 mvn -DskipTests clean package  \
-pl streamingpro-spark-2.0 -am  \
-Ponline -Pscala-2.11  \
-Phive-thrift-server \
-Pspark-2.2.0 \
-Pdsl-legacy \
-Pcrawler \
-Pshade 

运行的json脚本如下：
{
  "test": {
    "desc": "测试",
    "strategy": "streaming.core.strategy.SparkStreamingStrategy",
    "algorithm": [],
    "ref": [
      "testJoinTable"
    ],
    "compositor": [
      {
        "name": "streaming.core.compositor.spark.streaming.source.MockInputStreamCompositor",
        "params": [{"data1":["1","2","3"]}]
      },
      {
        "name": "streaming.core.compositor.spark.streaming.transformation.SingleColumnJSONCompositor",
        "params": [
          {
            "name": "a"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.streaming.transformation.JSONTableCompositor",
        "params": [
          {
            "tableName": "test"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.streaming.transformation.SQLCompositor",
        "params": [
          {
            "sql": "select a, \"5\" as b from test",
            "outputTableName": "test2"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.streaming.transformation.SQLCompositor",
        "params": [
          {
            "sql": "select t2.a,t2.b from test2 t2, test t3 where t2.a = t3.a"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.streaming.output.SQLPrintOutputCompositor",
        "params": [
          {
          }
        ]
      }
    ],
    "configParams": {
    }
  },
  "testJoinTable": {
    "desc": "测试",
    "strategy": "streaming.core.strategy.SparkStreamingRefStrategy",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "streaming.core.compositor.spark.source.MockJsonCompositor",
        "params": [
          {"a":"3"},
          {"a":"4"},
          {"a":"5"}
        ]
      },
      {
        "name": "streaming.core.compositor.spark.transformation.JSONTableCompositor",
        "params": [
          {
            "tableName": "testJoinTable"
          }
        ]
      }
    ],
    "configParams": {
    }
  }
}
存在很多class缺失的问题， 请大神帮忙看下，是不是这些class不需要，可以用其他的class替换？，谢谢！

**Comment by xieshunqiao** [comment]
你好，我也遇到了同样的问题，
Exception in thread "main" java.lang.ClassNotFoundException: streaming.core.compositor.spark.streaming.transformation.JSONTableCompositor
查看streamingpro releases页中的 streamingpro-spark-2.0-1.1.0.jar，发现Jar中是没有这个Class的。
下载Source code (zip)，发现streamingpro-spark-2.0跟streamingpro-spark项目下都有streaming.core.compositor.spark.streaming.transformation这个包，streamingpro-spark中有streaming.core.compositor.spark.streaming.transformation.JSONTableCompositor却没有被打包到jar中。（其他几个类也是如此）
那么，如果现在需要使用这些Class，是否需要通过下载Source code (zip)重新编译打包使用？

**Comment by xieshunqiao** [comment]
@allwefantasy 你好。
问题如上，另外
streaming/common/DefaultShortNameMapping.scala
这里shortName引用的部分Class,在jar中找不到。例如，使用的时候出现此异常 java.lang.ClassNotFoundException: streaming.core.compositor.spark.streaming.transformation.JSONTableCompositor
能帮忙解答一下吗？
