### ISSUE TITLE
Share some successful case with Json config file

### ISSUE THREAD

**Issue by robin-su** [byzer-org/byzer-lang#201]

**Comment by robin-su** [comment]
# 场景一：查询Parquet，并持久化到Mysql
{
  "scalamaptojson": {
    "desc": "测试",
    "strategy": "spark",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "batch.sources",
		"params": [{
                 "format":"parquet",
                 "path":"/tmp/venus_waf/collectDate=20180323/deviceType=WAF/1521791526672.parquet",  
                 "outputTable": "hdfstest"				 
             }]
      },
      {
        "name": "batch.sql",
        "params": [
          {
            "sql": "select hdfstest.*  from hdfstest limit 10",
            "outputTableName": "test1"
          }
        ]
      },
      {
        "name": "batch.sql",
        "params": [
          {
            "sql": "SELECT     DST_IP,   DEVICE_TYPE,  COLLECT_IP,  EQU_IP,  SRC_IP,  PROTOCOL,  SRC_PORT,  ACTION,  DST_PORT,  SERVERITY,  COLLECT_TIME,  CREATE_TIME,  ATTACK_TYPE,  TAG,  TYPE FROM  test1 ",
            "outputTableName": "test2"
          }
        ]
      },
       {
        "name": "batch.outputs",
        "params": [
          {
			  "url":"jdbc:mysql://xxx.xxx.xxx.xxx:3306/analysisTest?user=username&password=password",
              "dbtable":"test_table",
              "driver":"com.mysql.jdbc.Driver",
              "path": "-",
              "format": "jdbc",
			  "mode" : "Append",
			  "inputTableName": "test2"
          }
        ]
      }
    ],
    "configParams": {}
  }
}

# 场景2：从hdfs文件中读取文件，spark sql查询并持久化到mysql,注意Hdfs保存为JSON文件
{
  "scalamaptojson": {
    "desc": "测试",
    "strategy": "streaming.core.strategy.SparkStreamingStrategy",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "streaming.core.compositor.spark.source.MultiSQLSourceCompositor",
        "params": [ {
              "path": "/yarn/offline-platform/tmp/testData.txt",
              "format": "json",
              "outputTable": "hdfstest"
            }
                ]
      },
      {
        "name": "streaming.core.compositor.spark.transformation.SQLCompositor",
        "params": [
          {
            "sql": "select hdfstest.*  from hdfstest",
            "outputTableName": "test1"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.transformation.SQLCompositor",
        "params": [
          {
            "sql": "select deviceType, SRC_IP, DST_IP, DST_PORT, PEAK_FLOW, ACTION, POLICY, COLLECT_TIME, uuid, eventType_s, PRIORITY, SRC_PORT, PROTOCOL from test1",
            "outputTableName": "test2"
          }
        ]
      },
      {
        "name": "streaming.core.compositor.spark.output.MultiSQLOutputCompositor",
        "params": [
          {
                          "url":"jdbc:mysql://xxx.xxx.xxx.xxx:3306/analysisTest?user=username&password=password",
              "dbtable":"testhdfs",
              "driver":"com.mysql.jdbc.Driver",
              "path": "-",
              "format": "jdbc",
                          "mode" : "Append",
                          "inputTableName": "test2"
          }
        ]
      }
    ],
    "configParams": {}
  }
}

**Comment by allwefantasy** [comment]
1. 你可以使用重新编辑下，然后使用 "```json ```" 括起来你的代码，这样样式会好看很多。
2. 对于默认的模块，可以一直使用类似`batch.outputs `简写。

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
