### ISSUE TITLE
StreamingPro Driver端进程无法关闭问题

### ISSUE THREAD

**Issue by robin-su** [byzer-org/byzer-lang#208]
各位大佬好，我想问下StreamingPro每次运行批处理之后，我使用的是yarn client模式启动的，但是每次批处理运行完之后，executor端进程有被杀死，但是driver始终没有运行着而不会自动退出。请问下这个是怎么回事呢？以下是我的启动脚本和json配置：

- 启动脚本如下：

#!/bin/sh

var=$1
APP_NAME=$(basename ${var%.*})

function fireApplication() {
nohup spark2-submit \
--class streaming.core.StreamingApp \
--master local[2] \
--name testOnYarn \
streamingpro-spark-2.0-1.1.0.jar \
-streaming.name test \
-streaming.platform spark \
-streaming.spark.service  false \
-streaming.job.file.path hdfs://xxx:8020/yarn/offline-platform/tmp/${APP_NAME}.json  >> log/${APP_NAME}.log 2>&1 &
}

function fireYarnApplication() {
nohup spark2-submit \
    --class streaming.core.StreamingApp \
    --master yarn \
    --deploy-mode client \
    --executor-memory 2G \
    --num-executors 3 \
    --executor-cores 2 \
    --driver-memory 2G \
    --name test \
    streamingpro-spark-2.0-1.1.0.jar \
    -streaming.name test \
    -streaming.platform spark \
    -streaming.spark.service  false \
    -streaming.job.file.path hdfs://asap192:8020/yarn/offline-platform/tmp/${APP_NAME}.json >> log/${APP_NAME}.log 2>&1 &
}

if [ $# -gt 1 ]
then
   fireYarnApplication
else
   fireApplication
fi

- 配置文件如下：

{
  "scalamaptojson": {
    "desc": "测试",
    "strategy": "spark",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "batch.sources",
                "params": [{
                 "format":"parquet",
                 "path":"/tmp/venus_waf/testData.parquet",  
                 "outputTable": "hdfstest"                               
             }]
      },
      {
        "name": "batch.sql",
        "params": [
          {
            "sql": "select hdfstest.*  from hdfstest",
            "outputTableName": "test1"
          }
        ]
      },
      {
        "name": "batch.sql",
        "params": [
          {
            "sql": "SELECT     DST_IP,   DEVICE_TYPE,  COLLECT_IP,  EQU_IP,  SRC_IP,  PROTOCOL,  SRC_PORT,  ACTION,  DST_PORT,  SERVERITY,  COLLECT_TIME,  CREATE_TIME,  ATTACK_TYPE,  TAG,  TYPE FROM  test1 ",
            "outputTableName": "test2"
          }
        ]
      },
       {
        "name": "batch.outputs",
        "params": [
          {
                          "url":"jdbc:mysql://xxx.xxx.xxx.xxx:3306/analysisTest?user=root&password=123",
              "dbtable":"test_table",
              "driver":"com.mysql.jdbc.Driver",
              "path": "-",
              "format": "jdbc",
                          "mode" : "Append",
                          "inputTableName": "test2"
          }
        ]
      }
    ],
    "configParams": {}
  }
}

**Comment by RebieKong** [comment]
@allwefantasy 这是一个没有使用carbondata也异常的情况。。

**Comment by allwefantasy** [comment]
这里有个默认参数的bug,你有两个解决办法：

1. 我刚提交了一个hotfix,修复了这个问题，你需要重新编译打包下。
2. 你也可以启动的时候添加两个新的参数

```
 -streaming.unitest.awaitTermination false
 -streaming.unitest.startRuntime false
```

**Comment by allwefantasy** [comment]
@robin-su 好像还有些问题。我弄好了之后会再通知你。

**Comment by allwefantasy** [comment]
@robin-su 已经解决了。你需要重新编译一下。

**Comment by allwefantasy** [comment]
@RebieKong 已经解决了。你需要重新编译一下。

**Comment by robin-su** [comment]
@allwefantasy  谢谢哈
