### ISSUE TITLE
 [JSON-Based] 增加一些时间常量参数

### ISSUE THREAD

**Issue by RebieKong** [byzer-org/byzer-lang#210]
参考 PR #159 的写法
目前有3个工作：
1. 常用的时间常量的枚举工作
2. 常用的时间格式的枚举工作
3. 替位符的格式讨论工作

**Comment by RebieKong** [comment]
时间常量可以抽象为：
1. n小时前
2. n小时后
3. n天前
4. n天后
5. n月前
6. n月后
7. n年前
8. n年后

常用时间常量应当被上述的表述所包含，实际上时间常量应当是上述的一些特殊情况

常用的时间常量：
1. 今天
2. 一小时后
3. 一小时前
4. 明天->一天后
5. 七天后
6. 一个月后
7. 一年后
8. 昨天->一天前
9. 七天前
10. 一个月前
11. 一年前

希望得到补充

**Comment by RebieKong** [comment]
时间格式应当接受自定义属性，并可以使用预定义格式，时间格式参考SimpleDatetimeFormat

预定义时间格式：
1. yyyy-MM-dd
2. yyyyMMdd
3. yyyy-MM-dd HH:mm:ss
4. yyyyMMddHHmmss

希望得到补充

**Comment by cfmcgrady** [comment]
@RebieKong set语法是支持将`sql`运行结果赋予变量的，参考[PR-181](https://github.com/allwefantasy/streamingpro/pull/181)

**Comment by RebieKong** [comment]
@cfmcgrady 那个是mlsql，我想在json配置文件中添加此功能
