### ISSUE TITLE
kafka版本问题

### ISSUE THREAD

**Issue by Tom-YJ** [byzer-org/byzer-lang#211]
你好，我使用spark2.2-1.10 中ss 读取kafka（本地kafka版本为1.1.0）数据，
配置为format :kafka，subscribe : topic
但是根据日志显示信息报的订阅版本为0.9.0-kafka-2.0.2,还报没有NoSuchMethodError:org.apache.kafka.clients.consumer.KafkaConsumer.subscribe...
请问，这是什么原因导致的？应该如何解决呢？

望解答，谢谢！！！

**Comment by Tom-YJ** [comment]
@allwefantasy

**Comment by allwefantasy** [comment]
1. 你是使用mlsql还是json?
2. 能把对应配置贴出来么
3. 使用过程中除了streamingpro包有没有额外的包？

**Comment by Tom-YJ** [comment]
使用的json,没有额外的包
配置类似这个：
{
    "scalamaptojson": {
        "desc": "测试",
        "strategy": "spark",
        "algorithm": [],
        "ref": [],
        "compositor": [{
                "name": "ss.sources",
                "params": [{
                    "format": "kafka",
                    "kafka.bootstrap.servers": "ip:port",
                    "subscribe": "spark-test",
                    "outputTable": "test",
                    "path": "-"
                }]
            },
            {
                "name": "ss.sql",
                "params": [{
                    "sql": "select CAST(value AS STRING) as json from test",
                    "outputTableName": "test1"
                }
                ]
            },
            {
                "name": "ss.sql",
                "params":[{
                    "sql": "select get_json_object(json, '$.people.type') as type, get_json_object(json, '$.payload') as payload, get_json_object(json, '$.name')  as name from test1",
                    "outputTableName": "test2" 
                }
                ]
            },
            {
                "name": "ss.sql",
                "params":[{
                    "sql": "select name, new from test2 lateral view explode(split(substr(test2.payload,2,length(test2.payload) - 2),',')) exploded as new", 
                    "outputTableName": "test3" 
                }
                ]
            },
            {
                "name": "ss.outputs",
                "params": [{
                    "mode": "append",
                    "format": "console",
                    "inputTableName": "test3",
                    "path": "-"
                },{
                    "mode": "append",
                    "format": "console",
                    "inputTableName": "test2",
                    "path": "-"
                }
                ]
            }
        ],
        "configParams": {}
    }
}

**Comment by Tom-YJ** [comment]
@allwefantasy

**Comment by allwefantasy** [comment]
日志错误也可以贴出来哦

**Comment by Tom-YJ** [comment]
@allwefantasy 
具体日子拿不出来呀，主要就是这个错误：NoSuchMethodError:org.apache.kafka.clients.consumer.KafkaConsumer.subscribe...

可以给一个kafka sparkstreaming 和 batch 表之间的一个关联json示例吗？ 通过sparkstreaming 消费没有问题

**Comment by allwefantasy** [comment]
ss 我测试是没有问题的。而且默认structured streaming就是支持的kafka 1.1.0。你可以再确认下是否连的你本地的kafka,以及版本是否正确。

spark streaming的例子是一样的。只需要把ss换成stream即可。
比如ss.sources 换成 stream.sources。 然后sources的subscribe关坚持换成topic好像就可以了。

**Comment by Tom-YJ** [comment]
好的，我先测试一下stream,多谢指导

**Comment by Tom-YJ** [comment]
测试stream成功，但是增加kafka参数时发现kafka参数有些为<0.10版本参数，如auto.offset.reset需要使用smallest,当使用earliest时报参数异常问题，但kafka服务地址配置可使用bootstrap.servers

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
