### ISSUE TITLE
看了下项目的依赖关系.基本是无法自编译的

### ISSUE THREAD

**Issue by ansjsun** [byzer-org/byzer-lang#22]
看了下项目的依赖关系.基本是无法自编译的

依赖active_orm , active_orm 依赖.两个csdn的内部jar包.

这两个内部jar包不开源.

建议两种方式.将jar包直接放到工程中.或者不用那两个jar..

**Comment by allwefantasy** [comment]
已经解决。编译步骤参考： 
https://github.com/allwefantasy/streamingpro/wiki/Build
