### ISSUE TITLE
spark 2.1 support carbondata 1.1.0  mvn编译出错

### ISSUE THREAD

**Issue by lbqgithub** [byzer-org/byzer-lang#24]
Spark does not yet support its JDBC component for spark2.1,Scala2.11?
ERROR as below:

[ERROR] D:\forstr\streamingpro-car\streamingpro-spark-2.0\src\main\java\streaming\core\strategy\platform\SparkRuntime.scala:9: error: object thriftserver is not a member of package org.apache.spark.sql.hive
[INFO] import org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
[INFO]                                  ^
[ERROR] D:\forstr\streamingpro-car\streamingpro-spark-2.0\src\main\java\streaming\core\strategy\platform\SparkRuntime.scala:94: error: not found: value HiveThriftServer2
[INFO]     HiveThriftServer2.startWithContext(sparkSession.sqlContext.asInstanceOf[HiveContext])

**Comment by allwefantasy** [comment]
Make sure hive-thrift-server profile is selected.

**Comment by lbqgithub** [comment]
pom.xml add dependency ：

<dependency>
<groupId>org.apache.spark</groupId>
<artifactId>spark-hive-thriftserver_2.10</artifactId>
<version>2.1.0</version>
</dependency>
