### ISSUE TITLE
flink 与 redis 流处理问题

### ISSUE THREAD

**Issue by lstq-lab** [byzer-org/byzer-lang#241]
1、kafka json格式，时间窗口内拉取到的数据，如何根据key关联查询redis数据 ？

2、批处理的DataSet 与流处理的DataStream为2套不同的运行时环境的数据结构，有时候流数据需要关联查询静态数据， 这2个不同的接口无法实现， 求解。

**Comment by lstq-lab** [comment]
Spark对于批处理和流式计算，都是用的相同的抽象：RDD，这样很方便这两种计算合并起来表示。而Flink这两者分为了DataSet和DataStream，相比Spark，这个设计算是一个糟糕的设计。

**Comment by allwefantasy** [comment]
We will close this issue if you do not have other questions. If need, please reopen this issue.
