### ISSUE TITLE
Compiling Errors

### ISSUE THREAD

**Issue by caiyt2001** [byzer-org/byzer-lang#260]
按文档先编译
mvn install -Pscala-2.11 -Pjetty-9 -Pweb-include-jetty-9
成功
然后编译
mvn -DskipTests clean package  -pl streamingpro-spark-2.0 -am  -Ponline -Pscala-2.11  -Phive-thrift-server -Pspark-2.1.0 -Pdsl-legacy -Pshade
报错如下：这个是缺包吗？还是版本不对
![image](https://user-images.githubusercontent.com/35490928/40951997-23684350-68ac-11e8-820f-9d2baacb6403.png)

我的环境是spark-2.1.1-bin-hadoop-2.6.0-cdh5.8.2 有没有问题？

**Comment by allwefantasy** [comment]
目前只测试过2.2.0版本,其他版本我们在计划也做测试，但很可能会先同时支持spark 2.2.x,2.3.x。 
请使用 -Pspark-2.2.0  另外编译文档有所更新，请[参看](https://github.com/allwefantasy/streamingpro/blob/master/docs/compile.md)

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
