### ISSUE TITLE
vec_dense 不支持float型

### ISSUE THREAD

**Issue by pk3725069** [byzer-org/byzer-lang#279]
select vec_dense(array(1.0,2.0,7.0)) 不支持float型

**Comment by allwefantasy** [comment]
是会报错么？我这边测试是OK的。
![wx20180615-153959](https://user-images.githubusercontent.com/797758/41456240-6e851986-70b2-11e8-9c6f-044587967916.png)

**Comment by cfmcgrady** [comment]
原因是因为`vec_array`接受的是`Double`类型参数，而`array`方法生成的类型不一定是`Double`

**Comment by allwefantasy** [comment]
We will close this issue if you do not have other questions. If need, please reopen this issue.
