### ISSUE TITLE
建一个讨论群

### ISSUE THREAD

**Issue by csxuyang** [byzer-org/byzer-lang#29]
能否建一个讨论群，大家一起讨论问题啊，刚接触这个，看着好费劲

**Comment by iodone** [comment]
好多隐藏的配置，一个一个调试有点麻烦

**Comment by Yodeser** [comment]
建议[作者](allwefantasy)应该写个详细的开发文档放在Wiki里的。。。。大部分人要么无法使用要么困在复杂的配置里。。。

**Comment by YodesYang** [comment]
建议作者@allwefantasy 应该写个详细的开发文档放在Wiki里的。。。。大部分人要么无法使用要么困在复杂的配置里。。。

**Comment by 2efPer** [comment]
有群了吗？这项目我还没跑起来过
