### ISSUE TITLE
hive 示例？

### ISSUE THREAD

**Issue by Tom-YJ** [byzer-org/byzer-lang#292]
您好！
请问batch 访问hive数据库，除了知道-streaming.enableHiveSupport true，和--files /*/hive-site.xml  以外还需要其他配置吗？这边没有访问到hive数据库，有个配置示例最好了，谢谢

**Comment by Tom-YJ** [comment]
@allwefantasy

**Comment by allwefantasy** [comment]
不需要其他配置了。然后你直接用select 语句访问对应的库表即可。

**Comment by allwefantasy** [comment]
另外 hive-site.xml文件最好放到 YARN_CONFIG_DIR等环境变量中。否则你用client等模式可能会存在些问题。

**Comment by Tom-YJ** [comment]
我的启动参数配置如下：
#!/bin/bash
spark2-submit   --class streaming.core.StreamingApp \
--master $1 \
--num-executors 4 \
--driver-memory 1g \
--executor-memory 4g \
--executor-cores 1 \
--name gzstream2 \
file:///opt/yj/fullgoal/streamingpro-spark-2.0-1.1.0.jar    \
-streaming.enableHiveSupport true \
-streaming.name gzstream2    \
-streaming.platform $2 \
-streaming.job.file.path $3 \
-streaming.duration 15 

json中sql如下：  "name": "batch.sql",
        "params": [
          {
            "sql": "select count(*) cou from hyshf.store_sales,hyshf.household_demographics,hyshf.time_dim,hyshf.store where ss_sold_time_sk = time_dim.t_time_sk and ss_hdemo_s
k = household_demographics.hd_demo_sk and ss_store_sk = s_store_sk and time_dim.t_hour = 8 and time_dim.t_minute >= 30 and household_demographics.hd_dep_count = 5 and store.s_s
tore_name = 'ese' order by cou",
            "outputTableName": "test"
          }
        ]


启动报错，找不到数据库hyshf和表(数据库和表是存在的，直接使用sparksql可以查询成功)，报错如下：
18/06/22 12:48:01 WARN metastore.ObjectStore: Failed to get database hyrendde, returning NoSuchObjectException
18/06/22 12:48:01 ERROR dispatcher.StrategyDispatcher: 调用链路异常
org.apache.spark.sql.AnalysisException: Table or view not found: `hyrendde`.`store_sales`; line 1 pos 25;

您看看这有什么问题吗？
@allwefantasy

**Comment by Tom-YJ** [comment]
谢谢，问题解决了，是spark安装没有加hive服务！

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
