### ISSUE TITLE
提供一个新模块ModelExplainInPlace

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/byzer-lang#298]
提供一个新模块ModelExplainInPlace，第一阶段只支持sklearn模型，该模型可以加载sklearn模型，并且展现一些训练后的模型参数。

**Comment by wuheyi** [comment]
该模型的输入不是dataframe，和原有的模块不好统一。是否可以直接提供一个udf方法？
类似：model_explain(model_path, attributes) 。
其中attributes不填写时，显示全部属性

**Comment by allwefantasy** [comment]
有不少模块的输入df 都只是占位的，并不是作为真实输入。 采用函数的方式属于辅助方式。函数显示的方式不好，并且对于路径处理也比较困难。在MLSQL中是有主目录概念的，如果采用函数就比较麻烦了。

**Comment by wuheyi** [comment]
![image](https://user-images.githubusercontent.com/4252951/41805045-0030fb44-76d4-11e8-8ef2-efa8b4edc1f3.png)
为什么TaskContext.get()是空的，导致MonitorThread提前退出。
      while (!context.isInterrupted && !context.isCompleted) {
        Thread.sleep(2000)
      }
这一步执行不下去，因为context是空的，错误如下：
Exception in thread "Worker Monitor for python mlsql_sk_attributes.py" java.lang.NullPointerException
	at org.apache.spark.util.ExternalCommandRunner$MonitorThread.run(ExternalCommandRunner.scala:226)
但python程序其实运行起来了，也生成了我想要的数据
![image](https://user-images.githubusercontent.com/4252951/41805079-9a88e0f8-76d4-11e8-86a4-f455d881c3a0.png)

其中attributes.json是我自己加载模型获得的参数。

**Comment by wuheyi** [comment]
搞定了，在
     val res = ExternalCommandRunner.run(Seq(pythonPath, pythonScript.fileName),
      paramMap,
      MapType(StringType, MapType(StringType, StringType)),
      pythonScript.fileContent,
      pythonScript.fileName, modelPath = null, kafkaParam = null,
      validateData = null
    )
后少加了    res.foreach(f => f)
task目录最后需要清空，所以需要把结果文件写到/tmp路径

**Comment by allwefantasy** [comment]
ExternalCommandRunner 需要在算子里面执行，不能直接在driver端执行。其他实际使用例子中，也是 rdd.map(....) map里面使用ExternalCommandRunner。

**Comment by wuheyi** [comment]
需要将mlsql_sk_attributes.py放到resources-noline/python目录，否则线上环境会找不到文件报错
