### ISSUE TITLE
动态添加Job

### ISSUE THREAD

**Issue by yinchuanwang** [byzer-org/byzer-lang#3]
大神，现在所有的job都是放在一个spark app里面，所以所有的job的执行时间间隔都是一样的，能有办法实现不同的job的时间间隔不同？ 另外如果我job很多的情况下，都放在一个app里面会有问题？

**Comment by allwefantasy** [comment]
在一个spark app 实例里，没有办法实现不同Job 时间间隔不一致。

Q: 所以所有的job的执行时间间隔都是一样的，能有办法实现不同的job的时间间隔不同
A:  job 都放在同一个配置文件，然后启动时加上 streaming.jobs 参数指定需要启动的job 。这样配置文件统一了，根据时间分组，启动不同app 实例 

Q: 另外如果我job很多的情况下，都放在一个app里面会有问题？
 默认是顺序执行的。如果处理时间过程，可以通过spark 参数 spark.streaming.concurrentJobs 设置并行度。默认是1。 如果你单个Streaming实例资源有限，那么建议还是分开成多个实例执行比较好。

个人推荐：

最好是一个job 一个Streaming实例。资源科适当调小。这样你说的问题就都解决了。

**Comment by yinchuanwang** [comment]
谢谢大神。有时间的话，写篇介绍streamingpro的模块之间关系的文章拜，看了2天，还没完全看懂啊。:)

**Comment by allwefantasy** [comment]
首先我已经做了很多示例了，参看这些gist:

https://gist.github.com/allwefantasy

其次，批处理任务的所有Compositor 都是在：

streaming.core.compositor.spark.source 

流式处理的都在

streaming.core.compositor.spark.source.streaming 

下。 只要注意这个 差别就好。
