### ISSUE TITLE
信息检索常用评价指标的实现

### ISSUE THREAD

**Issue by btpeter** [byzer-org/byzer-lang#302]
在信息检索相关的排序任务中，评价指标除了准确率，还需要支持如下指标：
MAP (Mean average precision)
MRR (Mean reciprocal rank)
DCG (Discounted cumulative gain)
NDCG (Normalize Discounted cumulative gain)
各指标的解释可以参考：
https://blog.csdn.net/u010138758/article/details/69936041

**Comment by allwefantasy** [comment]
输入的数据是什么样的的？ 比如在混淆矩阵里，输入是预测和实际标注结果。在信息检索里，输入是什么呢？能够给出一个比较简单的例子？

**Comment by btpeter** [comment]
信息检索模型的输出本质也是个分类问题，包括真实值和预测值，一般是多分类（从无关到相同的score值,比如说0-3的某个int值）；不同的是输出变成了两个，分别是搜索的 query 和 返回的 document ，通常来说一个query回返回多个不同的document，最终输入评价指标中的格式为：

假设评价跨度为 0,1,2,3 ； 每个query返回的document数为3个

输入query   输入doc   真实值   预测值
q1               d1                3          2
q1               d2                1          1
q1               d3                1          2
q2               d5                0         0
q2               d6                3         2
q2               d9                3         3

**Comment by pigeon-geng** [comment]
评价指标核心还是，准确率  和 召回率
信息检索模型的输出：可以在比特的那个上面增加，文档位置

**Comment by btpeter** [comment]
@pigeon-geng 不是啊。。核心指标是 MAP MRR DCG NDCG。。。。

**Comment by pigeon-geng** [comment]
逃不过 标注数据

**Comment by allwefantasy** [comment]
不应该是讨论这些指标的输入输出以及计算规则么？

**Comment by allwefantasy** [comment]
We will close this issue if you do not have other questions. If need, please reopen this issue.
