### ISSUE TITLE
redis json配置

### ISSUE THREAD

**Issue by Tom-YJ** [byzer-org/byzer-lang#310]
你好，可以给一个redis 输入和输出的json配置示例吗？谢谢
@allwefantasy

**Comment by allwefantasy** [comment]
因为现在很少考虑json格式配置的，所以我也不确定是否能够支持。 不过mlsql脚本里是可以支持一部分的。可以在PR里找到一些蛛丝马迹[Redis 相关PR](https://github.com/allwefantasy/streamingpro/pulls?q=is%3Apr+redis+is%3Aclosed ) 。另外值得一提的是,Redis支持比较有限，我只是针对我司实际诉求添加了几个支持。

**Comment by allwefantasy** [comment]
输入应该是明显不支持的了。。。。

**Comment by Tom-YJ** [comment]
了解，谢谢解答

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
