### ISSUE TITLE
Mysql  测试数据被清空...

### ISSUE THREAD

**Issue by Tom-YJ** [byzer-org/byzer-lang#311]
测试了一个以mysql作为数据输入和输出的场景，具体如下：
起始情况下mysql无数据，通过spark streaming 消费将kafka中的读取和mysql中的数据做union 然后进行存储，model 类型 Overwrite。
遇到问题如下：
拉取kafka数据，第一次job成功将关联后的数据存储进mysql，可以查看到
第二次任务拉取的kafka数据为0条，mysql中存在第一次的数据，关联结果控制台打印正常有数据，但是查看mysql数据库时，发现没有数据。理论上来说，控制台输出表和mysql表为同一张表，为什么控制台打印的有数据而mysql中没有的？
@allwefantasy

**Comment by allwefantasy** [comment]
读取并且覆写同一张表是吧，这种做法没有实践过。能不能想办法不用这种方式？

**Comment by allwefantasy** [comment]
能不能比如这样操作： 先把mysql读取出来，并且存储成parquet文件，接着再从kafka拿数据和这个parquet文件做join,最后再覆写mysql.这种模式应该不会有问题。

**Comment by Tom-YJ** [comment]
了解，谢谢

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
