### ISSUE TITLE
多个模型并行训练

### ISSUE THREAD

**Issue by pk3725069** [byzer-org/byzer-lang#333]
预测时,参数algIndex不能对应训练时候的fitParam.index

**Comment by allwefantasy** [comment]
能贴一段你使用的脚本么？ 目前我们使用上是ok的。

**Comment by allwefantasy** [comment]
可能确实存在这个问题。我们很快会发一个PR上来。

**Comment by allwefantasy** [comment]
已经解决，参看： https://github.com/allwefantasy/streamingpro/pull/335

**Comment by wuheyi** [comment]
同一个模型使用不同数据集的并行训练后续也可以支持下，上次我看到顺子一次次跑模型，然后选acc最高的作为最终的模型。

**Comment by cfmcgrady** [comment]
@wuheyi 新建个issue讨论
