### ISSUE TITLE
Python Worker闲置一分钟会导致被监控线程杀掉

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/byzer-lang#344]
这个选项应该是可配置的，但是spark 并不支持这个配置，需要重写。

**Comment by allwefantasy** [comment]
加载模型时间过长

**Comment by allwefantasy** [comment]
如果去掉这个功能，模型卸载/更新会变得非常困难。

**Comment by cfmcgrady** [comment]
[SPARK-24405](https://jira.apache.org/jira/browse/SPARK-24405)有人在JIRA上提了ISSUE，不过似乎并没有动静，需要想想别的方法。

**Comment by allwefantasy** [comment]
现在一个比较合理的方式是： 
1. 如果是部署成API,那么这个时间会很长，或者永不过时。修正好的版本会是24h限制后背杀死。
2. 如果是普通的流式或者批处理，则按默认配置，1m 限制后会被杀死。

**Comment by allwefantasy** [comment]
启动时配置参数 -streaming.deploy.rest.api true  。这个参数表明会将streamingpro部署成一个API服务，之后如果python worker一旦启动，24小时没有接受到消息才会被杀死。
