### ISSUE TITLE
Table 'spark_job.t_spark_job_parameter' doesn't exist

### ISSUE THREAD

**Issue by lonly197** [byzer-org/byzer-lang#35]
When I visit this page（http://{host}:9004/submit_job.html）, I encountered this error： 

![image](https://user-images.githubusercontent.com/7350356/29398613-2b5842fc-8358-11e7-9b1a-35ffb3f25136.png)

I checked the spark_jobs_2017-07-18.sql，but I did not find any description about the table 'spark_job.t_spark_job_parameter'

**Comment by allwefantasy** [comment]
已经更新了文件。spark_jobs_2017-08-20.sql
