### ISSUE TITLE
如何实现分页查询数据库，提高加载效率并防止数据传输倾斜 ？

### ISSUE THREAD

**Issue by lstq-lab** [byzer-org/byzer-lang#367]
利用集群的处理能力， 如何实现分页查询数据库，提高加载效率并防止数据传输倾斜 ？

**Comment by allwefantasy** [comment]
提升并发就可以了，具体参看spark的MySQL数据源API,当然最后还是看你的mysql承受能力。 分页只能做假分页。，比如你可以每次都取一万条，我觉得已经足够了。另外数据倾斜的话，你只要把mysql里的表切分均匀就没啥问题，计算的数据倾斜只能case by case了。
