### ISSUE TITLE
streamingpro-1.1.2 编译 streamingpro-mlsql 报错

### ISSUE THREAD

**Issue by lipf19860104** [byzer-org/byzer-lang#370]
`-DskipTests clean package  -pl streamingpro-mlsql -am -Ponline -Pscala-2.11  -Phive-thrift-server -Pspark-2.1.0 -Pdsl-legacy -Pshade 进行编译 ` 

使用上面命令编译，报错如下，这是什么原因导致的？

![image](https://user-images.githubusercontent.com/13567711/42978563-294ff34a-8c00-11e8-8167-27379ddd0c15.png)

代码部分也有报错
![image](https://user-images.githubusercontent.com/13567711/42978712-067b50b6-8c01-11e8-9ff1-62ca086e9449.png)

**Comment by lipf19860104** [comment]
本地 scala 是2.11.8， 是不是我漏掉了什么？

**Comment by allwefantasy** [comment]
现在测试过的版本是 spark 2.2.0  请用这个语句：

```
mvn -DskipTests clean package  -pl streamingpro-mlsql -am  -Ponline -Pscala-2.11  -Phive-thrift-server -Pspark-2.2.0 -Pdsl-legacy -Pcrawler -Pshade -Popencv-support -Pcarbondata
```

**Comment by lipf19860104** [comment]
服务器上的 spark 版本是 2.1.0 的，使用 2.2.0 编译的包有些功能会有问题，比如持久化数据到 mysql。 看来得用 2.1.0 的 api 改动下源码重新编译了
