### ISSUE TITLE
希望在使用spark与sklearn等机器学习模块在输入模型参数时，如果这时输入的参数在当前模块不支持或输入错误时能报错。

### ISSUE THREAD

**Issue by cgldtsci** [byzer-org/byzer-lang#428]
希望在使用spark与sklearn等机器学习模块在输入模型参数时，如果这时输入的参数在当前模块不支持或输入错误时能报错。这样就不会错认为输入的参数是成功的。

**Comment by allwefantasy** [comment]
1. SKlearn是使用PythonAlg模块直接引入python文件的方式使用的，所以可以可以直接通过修改python-mlsql项目直接解决。
2. Spark 目前是通过反射的方式将参数设置进去。你配置了一个错误的参数，其实系统并不知道这个参数是不是错误的（因为这个参数可能是其他的地方要用的）。但是系统可以收集到所有可用的参数。我的想法是提供一个模块，该模块输入其他模块的名字，可以得到对应模块的所有可配置参数。

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
