### ISSUE TITLE
数据库查询可否用 like？

### ISSUE THREAD

**Issue by Mvpanswer7** [byzer-org/byzer-lang#44]
看到源码里数据库部分类似这样：
`from(DB.tSparkJobParameter)(s => where(s.id === id) select (s)).singleOption`
请问这种数据库查询 在查询字符串的时候能否使用like来做呢？比如
`from(DB.tSparkJobParameter)(s => where(s.name like name) select (s)).singleOption`

**Comment by mvasr7** [comment]
饿，已解决
`from(DB.tSparkJobParameter)(s => where(s.name like s"%${name}%") select (s)).tolist`
