### ISSUE TITLE
任务可以续跑吗

### ISSUE THREAD

**Issue by foreverjay** [byzer-org/byzer-lang#459]
我想咨询下，spark任务可以续跑吗？比如一个任务有10步，跑到第3步错了，下次能直接从3恢复吗

**Comment by allwefantasy** [comment]
目前是不支持自动的。如果你知道第三部错了，你可以把前面的删除，直接从第三步执行。（set语法是不能删除的）

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
