### ISSUE TITLE
新版本把rest api支持json添加job的干掉了吗？

### ISSUE THREAD

**Issue by foreverjay** [byzer-org/byzer-lang#468]
新版本把rest api支持json添加job的干掉了吗？

**Comment by allwefantasy** [comment]
新版本 如果用server mode ，是可以随时添加或者删除流式任务的。参看这个：https://github.com/allwefantasy/streamingpro/blob/master/docs/en/mlsql-stream.md

**Comment by foreverjay** [comment]
这个是sql模式的，有支持json模式的吗

**Comment by allwefantasy** [comment]
Yes ,we have remove the feature from appliction mode.
We will close this issue. You can reopen it or create a new one if you have any other questions.
