### ISSUE TITLE
关于样本不平均

### ISSUE THREAD

**Issue by CoderOverflow** [byzer-org/byzer-lang#475]
关于样本不平均 小节 提出的这个多模型的解决方法，可有相关文档说明，或者论文引用？

[样本不平均](https://github.com/allwefantasy/streamingpro/blob/master/docs/wow.md#%E6%A0%B7%E6%9C%AC%E4%B8%8D%E5%9D%87%E8%A1%A1%E9%97%AE%E9%A2%98)

找到文章
[In-classification-how-do-you-handle-an-unbalanced-training-set](https://www.quora.com/In-classification-how-do-you-handle-an-unbalanced-training-set)  里面提到的第二种说法和你的方案有点接近，但是多模型聚合用的是平均。

另外多模型下 结果汇总的函数可以配置吗？
有没有具体的SQL化的例子，来说明一下怎么操作?

**Comment by allwefantasy** [comment]
This solution is recommended by my colleague. For now, it only picks the model with the highest estimated value(actually the models are generated by the same algorithm, but they are feeded with diffrent dataset).

Here is an example:

```sql
load libsvm.`/sample_libsvm_data.txt` as data;

train data as NaiveBayes.`/tmp/bayes_model` where multiModels="true";

register NaiveBayes.`/tmp/bayes_model` as bayes_predict;

select bayes_predict(features) as predict_label, label  from data as result;

save overwrite result as json.`/tmp/result`;

select * from result as output;
```

**Comment by allwefantasy** [comment]
In StreamingPro, it's easy to inject your implementation.  Here  how we implement RandomForest:

```scala
class SQLRandomForest extends SQLAlg with Functions {
  override def train(df: DataFrame, path: String, params: Map[String, String]): Unit = {
    trainModels[RandomForestClassificationModel](df, path, params, () => {
      new RandomForestClassifier()
    })
  }

  override def load(sparkSession: SparkSession, path: String, params: Map[String, String]): Any = {
    loadModels(path, (tempPath) => {
      RandomForestClassificationModel.load(tempPath)
    })
  }

  override def predict(sparkSession: SparkSession, _model: Any, name: String, params: Map[String, String]): UserDefinedFunction = {
    predict_classification(sparkSession, _model, name)
  }
}
```

All you need is extend SQLAlg , and SQLAlg is  in streamingpro-api module which is used to make you easy to develop new modules for StreamingPro.

When you want to define your own strategy to evluate the score, you can replace the load implemation.

**Comment by CoderOverflow** [comment]
That makes sense
