### ISSUE TITLE
com.google.inject.CreationException: Guice creation errors

### ISSUE THREAD

**Issue by lonly197** [byzer-org/byzer-lang#48]
**Version**
1.0.0

**Reproduce conditions**
```
spark-submit  \
--conf "spark.ui.port=4041" \
--conf "spark.sql.codegen=true" \
--class streaming.core.StreamingApp \
--master local[2] \
--name sql-interactive \
$SHOME/streamingpro-spark-2.0-1.0.0.jar  \
-streaming.name sql-interactive    \
-streaming.job.file.path file://$SHOME/empty.json \
-streaming.platform spark   \
-streaming.rest true   \
-streaming.driver.port 9003   \
-streaming.spark.service true \
-streaming.thrift true \
-streaming.enableHiveSupport true
```
When I run the streamingpro in rest mode, I have encountered this problem。
![image](https://user-images.githubusercontent.com/7350356/30093992-9ab955ac-92fb-11e7-8f0f-aebb421cd026.png)
![image](https://user-images.githubusercontent.com/7350356/30094001-a7cc31d8-92fb-11e7-8249-a57ecebb5d38.png)

**Comment by allwefantasy** [comment]
你使用的是spark 什么版本？ 可能你的spark-submit
包含了一些额外的库(httpclient),这个库和streamingpro自带的版本上有冲突。

**Comment by lonly197** [comment]
spark2.1.0.2.6.0.3-8(hdp2.6)

**Comment by allwefantasy** [comment]
应该是我说的那个问题。你能不使用hdp的版本的么？直接下载一个社区版的运行？
