### ISSUE TITLE
manager能否动态读取配置文件

### ISSUE THREAD

**Issue by Mvpanswer7** [byzer-org/byzer-lang#49]
最近在基于manager做二次开发，每次修改完application.yml之后都要重新编译，请问有没有方法可以让manager动态的加载配置？？？不用每次都编译一遍，比如ip地址、端口这些，改下ip就要重新编译一遍，贼麻烦

**Comment by allwefantasy** [comment]
可以的。晚点我加个功能，可以指定配置文件地址即可。

**Comment by mvasr7** [comment]
多谢~

**Comment by jinky2004** [comment]
请问下，你manager页面访问是怎么访问的， url怎么填写的?
我用http://192.168.1.191:9000/test.html 这种都是返回404的错误 @Mvpanswer7 
谢谢！

**Comment by mvasr7** [comment]
@jinky2004 试试http://192.168.1.191:9000/jobs.html ？ip和端口的配置在application.yml里
