### ISSUE TITLE
集群yarn-client 模式下 train RateSampler模型，save 模型结果的时候出现 no lease 问题

### ISSUE THREAD

**Issue by iodone** [byzer-org/byzer-lang#491]
多个task写同一个parquet文件造成的？具体错误
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /user/spark//data/dmp/ratesampler/ratesampler/_temporary/0/_temporary/attempt_20180904182530_0015_m_000001_1/part-00001-c063cc1c-8ab9-4163-a9d6-698b7cde7f83-c000.snappy.parquet (inode 5765108): File does not exist

另外训练CorpusExplainInPlace也用同样问题

在本地Local模式下无此问题

**Comment by allwefantasy** [comment]
Can you paste more exception msg and the script of  RateSampler ?

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
