### ISSUE TITLE
Kafka内容解析支撑？

### ISSUE THREAD

**Issue by ghsuzzy** [byzer-org/byzer-lang#504]
kafka重点在于对value的解析，并加工处理；

比如
load kafka9.`` options `kafka.bootstrap.servers`="127.0.0.1:9092"
and `topics`="testM"
as newkafkatable1;

select CAST(value AS STRING) from newkafkatable1
as resultTable;
这里将value提取出来，是否可以进一步处理？
如value是Jason格式、Avro格式、Cvs格式
load Jason.`resultTable` as table0;
load Avro.`resultTable` as table1;
load Cvs.`resultTable`  as table2;

**Comment by CoderOverflow** [comment]
这样需要额外的数据的schema的吧

**Comment by ghsuzzy** [comment]
有好办法实现的吗？

**Comment by allwefantasy** [comment]
有的。

**Comment by allwefantasy** [comment]
One probably way:
```sql
load kafka9.`` options kafka.bootstrap.servers="127.0.0.1:9092"
and `topics`="testM" and `valueFormat`="json"
as newkafkatable1;
```

We add a new option valueFormat to specify the value format.

**Comment by allwefantasy** [comment]
The other way is we create a module:

```
run newkafkatable1 ValueFormat.`/tmp/abc` where valueFormat="json";
load parquet.`/tmp/abc/data` as newkafkatable2;
```

**Comment by pigeon-geng** [comment]
第一种load语法用起来更舒适一些。

**Comment by allwefantasy** [comment]
Yes, we prefer the first way which sees more intuitive.  We can expand Json to columns and make the other column in Kafka to be a new StructType. Simply merge Kafka columns into columns we get from Json value may cause name confliction issues.

**Comment by allwefantasy** [comment]
When load data from kafka, we can specify valueSchema  if the value is json.
valueSchema use a new grammar which is more easy to use:

```
st(field(a,st(field(a,string))))
```
st means Struct, field means StructField. 

```
st(
field(name,string),
field(name1,st(field(name2,array(string))))
)
```
equal to:

```
StructType(StructField(name,StringType,true), StructField(name1,StructType(StructField(name2,ArrayType(StringType,true),true)),true))
```


Example:
```sql
-- the stream name, should be uniq.
set streamName="streamExample";

-- mock some data.
set data='''
{"key":"yes","value":"{\"a\":{\"a\":\"no\"}}","topic":"test","partition":0,"offset":0,"timestamp":"2008-01-24 18:01:01.001","timestampType":0}
{"key":"yes","value":"{\"a\":{\"a\":\"no\"}}","topic":"test","partition":0,"offset":1,"timestamp":"2008-01-24 18:01:01.002","timestampType":0}
{"key":"yes","value":"{\"a\":{\"a\":\"no\"}}","topic":"test","partition":0,"offset":2,"timestamp":"2008-01-24 18:01:01.003","timestampType":0}
{"key":"yes","value":"{\"a\":{\"a\":\"no\"}}","topic":"test","partition":0,"offset":3,"timestamp":"2008-01-24 18:01:01.003","timestampType":0}
{"key":"yes","value":"{\"a\":{\"a\":\"no\"}}","topic":"test","partition":0,"offset":4,"timestamp":"2008-01-24 18:01:01.003","timestampType":0}
{"key":"yes","value":"{\"a\":{\"a\":\"no\"}}","topic":"test","partition":0,"offset":5,"timestamp":"2008-01-24 18:01:01.003","timestampType":0}
''';

-- load data as table
load jsonStr.`data` as datasource;

-- convert table as stream source
load mockStream.`datasource` options 
stepSizeRange="0-3"
and valueSchema="st(field(a,st(field(a,string))))"
as newkafkatable1;

-- aggregation 
select a.a,kafkaValue.topic  from newkafkatable1
as table21;

-- output the the result to console.
save append table21  
as console.`` 
options mode="Append"
and duration="10"
and checkpointLocation="/tmp/cpl3";

```

**Comment by allwefantasy** [comment]
We will plan to support more formats and try to infer the schema automatically.

**Comment by ghsuzzy** [comment]
上面json方式，确实方便，但非常苦涩难理解，json多时，都会把自己看晕，能否更直观
比如
{"key":"yes","value":"{\"a\":{\"a\":\"no\"}}","topic":"test","partition":0,"offset":0,"timestamp":"2008-01-24 18:01:01.001","timestampType":0}
valueSchema="key as key:string， value.a.a as valuea:string , topic as topic:string, partition as partition:int,  timestamp as timestamp: timestamp, timestampType as timestampType:int"

@allwefantasy

**Comment by allwefantasy** [comment]
Already support csv/json . see:  https://github.com/allwefantasy/streamingpro/pull/536

**Comment by allwefantasy** [comment]
@ghsuzzy  valueSchema="st(field(a,st(field(a,string))))"  is not json format.

```
st(field(column1,string),field(column2,string),field(column3,string))
```
This is not json format.  
If you are familiar with Spark StructType ,you will find they are really close. st equal to StructType, field equal 
to StructField, string equal to StringType.  Following datatypes are supported now:  

1. st
1. field
1. string
1. float
1. double
1. integer
1. short
1. date
1. binary
1. map
1. array

For example, you can use map like this:

```
st(field(column1,map(string,string)))
```

Or be more complicated:


```
st(field(column1,map(string,array(st(field(columnx,string))))))
```

**Comment by alexcd90** [comment]
i hope to this feature can support the confluent kafka system. for example schema-registry component.
