### ISSUE TITLE
【编译问题】[streamingpro-spark]编译报错

### ISSUE THREAD

**Issue by ghsuzzy** [byzer-org/byzer-lang#559]
这个包是没用起来嘛？
有些编译问题，请问下，是个什么情况？是否我的编译还要补充些东西

1. streaming.core.strategy.platform.SparkRuntime.scala这类下
没有此类 streaming.core.JobCanceller

2. org.apache.spark.sql.hive.thriftserver.HiveThriftServer3这类下
没有此些类 
import org.apache.spark.sql.SQLConf
import org.apache.spark.Logging
import org.apache.hive.service.server.HiveServerServerOptionsProcessor

3.org.apache.spark.sql.hive.thriftserver.HiveThriftServer3这类下
server.init(sqlContext.hiveconf)
报错：value hiveconf is not a member of org.apache.spark.sql.hive.HiveContext

4.org.apache.spark.sql.hive.thriftserver.HiveThriftServer3这类下
SparkSQLEnv.hiveContext = hiveContext
报错：value hiveContext is not a member of object org.apache.spark.sql.hive.thriftserver.SparkSQLEnv

5.org.apache.spark.sql.hive.thriftserver.HiveThriftServer3这类下
    hiveContext.metadataHive.setOut(new PrintStream(System.out, true, "UTF-8"))
    hiveContext.metadataHive.setInfo(new PrintStream(System.err, true, "UTF-8"))
    hiveContext.metadataHive.setError(new PrintStream(System.err, true, "UTF-8"))
报错：value metadataHive is not a member of org.apache.spark.sql.hive.HiveContext

**Comment by allwefantasy** [comment]
这个包是对spark 1.6.x 支持。已经不维护了，很快会移除。
