### ISSUE TITLE
支持夸库的表查询吗？比如mysql中test表和oracle中test_address表查询

### ISSUE THREAD

**Issue by SKY-Hao** [byzer-org/byzer-lang#563]
connect jdbc 
where driver="com.mysql.jdbc.Driver"
and url="jdbc:mysql://192.168.1.194:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false"
and driver="com.mysql.jdbc.Driver" 
and user="root"
and password="root"
as test;

connect jdbc 
where   driver="oracle.jdbc.driver.OracleDriver"
and url="jdbc:oracle:thin:@//192.168.1.194:1521/orcl"
and driver="oracle.jdbc.driver.OracleDriver"
and user="SCOTT" 
and password="redoop"
as oracle;

load jdbc.`test.test` 
as test;
load jdbc.`oracle.TEST`
as TEST;

select c.id as cid,c.name as cname,a.id as aid , a.name as aname 
from (select id,name from test) as c
left join
	(select id,name from TEST) as a
	on  c.id=a.id as d
	;
急需~~~！！！

**Comment by kaixinbuyu** [comment]
同问，load的时候支持sql statement吗？

connect jdbc
where driver="oracle.jdbc.driver.OracleDriver"
and url="jdbc:oracle:thin:@//192.168.1.194:1521/orcl"
and driver="oracle.jdbc.driver.OracleDriver"
and user="SCOTT"
and password="redoop"
as oracle;

load jdbc.test.test  
**where sql-statement="select * from xx where timestamp>'2018-01-01' and xxx='aa'"  <<------------像这种稍微带条件的sql**
as test;

**Comment by allwefantasy** [comment]
@SKY-Hao MLSQL是支持跨库关联的。如果使用oracle 你需要自己附带oracle的驱动。通过--jars带上。

@kaixinbuyu 暂时不支持这种sql-statement，你可以load完成后直接使用当做表使用，做过滤。

**Comment by SKY-Hao** [comment]
您好，我咨询您个问题mlsql；
支持Phoenix连接查询吗？连接方式什么样的，方便告知下吗？
急用，谢谢


| |
黄
|
|
hth_swp@163.com
|
签名由网易邮箱大师定制
在2018年10月9日 10:28，WilliamZhu<notifications@github.com> 写道：

@SKY-Hao MLSQL是支持跨库关联的。如果使用oracle 你需要自己附带oracle的驱动。通过--jars带上。

@kaixinbuyu 暂时不支持这种sql-statement，你可以load完成后直接使用当做表使用，做过滤。

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.

**Comment by SKY-Hao** [comment]
AttributeError: class StreamingProUDF_8d63b09b02224b2ca7e7ca29b08609e1 has no attribute 'apply'


分词的时候这个错什么意思，查出来是null


| |
黄
|
|
hth_swp@163.com
|
签名由网易邮箱大师定制

**Comment by SKY-Hao** [comment]
从mysql查数据保存到hive中，如何操作？


connect jdbc where driver="com.mysql.jdbc.Driver" 
and url="jdbc:mysql://192.168.0.26:3306/test"
and driver="com.mysql.jdbc.Driver"
and user="root" and password="root" as student;


load jdbc.`student.huang` as student;


select name,id,to_date(bdate, 'yyyyMMdd')as to_date from student as student;
connect jdbc where  
truncate="true"
and url="jdbc:hive2://192.168.0.26:10000/ods"
and driver="org.apache.hive.jdbc.HiveDriver"
and user="root"
and password=""
as hivea;


save append student  
as jdbc.`hivea.student01` 
options mode="true";






| |
黄
|
|
hth_swp@163.com
|
签名由网易邮箱大师定制
