### ISSUE TITLE
Can't insert into mysql  from Kafka in MLSQL stream 

### ISSUE THREAD

**Issue by foreverjay** [byzer-org/byzer-lang#576]
下面一段SQL运行都正常，而且mysql的表也建成功了，但数据就是插不进去，这是为什么呀？

-- the stream name, should be uniq.
set streamName="streamExample";

-- connect mysql as the data sink.
connect jdbc where driver="com.mysql.jdbc.Driver"
and url="xxx"
and driver="com.mysql.jdbc.Driver"
and user="xxx"
and password="xxx"
as mysql1;

load kafka9.`-` options `kafka.bootstrap.servers`="xxx:9092"
and `topics`="test"
as newkafkatable1;

-- aggregation 
select cast(value as string) as k,count(*) as c  from newkafkatable1 group by value
as table21;

-- save the data to mysql.
save append table21  
as jdbc.`mysql1.test1` 
options mode="Complete"
and implClass="org.apache.spark.sql.execution.streaming.JDBCSinkProvider"
and `driver-statement-0`="create table  if not exists test1(k TEXT,c BIGINT)"
and `statement-0`="insert into test1(k,c) values(?,?)"
and duration="3"
and checkpointLocation="/tmp/cpl0";

**Comment by foreverjay** [comment]
@allwefantasy 大神，帮忙看看，直接用您发布的包也不行

**Comment by foreverjay** [comment]
![image](https://user-images.githubusercontent.com/1586924/46844005-bdd8e000-ce07-11e8-9213-beb19e71fefc.png)

我感觉这一段有问题

**Comment by allwefantasy** [comment]
Is there any exception  thrown?

**Comment by allwefantasy** [comment]
We will close this issue if you do not have other questions. If need, please reopen this issue.

**Comment by 935205406** [comment]
I had the same problem, below is my script:
```
-- the stream name, should be uniq.
set streamName="streamExample";

-- connect mysql as the data sink.
connect jdbc where  
driver="com.mysql.jdbc.Driver"
and url="jdbc:mysql://dn1:3306/wow"
and driver="com.mysql.jdbc.Driver"
and user="XXXXX"
and password="XXXXX"
as mysql1;


-- mock some data.
set data='''
{"key":"yes","value":"no","topic":"test","partition":0,"offset":0,"timestamp":"2008-01-24 18:01:01.001","timestampType":0}
{"key":"yes","value":"no","topic":"test","partition":0,"offset":1,"timestamp":"2008-01-24 18:01:01.002","timestampType":0}
{"key":"yes","value":"no","topic":"test","partition":0,"offset":2,"timestamp":"2008-01-24 18:01:01.003","timestampType":0}
{"key":"yes","value":"no","topic":"test","partition":0,"offset":3,"timestamp":"2008-01-24 18:01:01.003","timestampType":0}
{"key":"yes","value":"no","topic":"test","partition":0,"offset":4,"timestamp":"2008-01-24 18:01:01.003","timestampType":0}
{"key":"yes","value":"no","topic":"test","partition":0,"offset":5,"timestamp":"2008-01-24 18:01:01.003","timestampType":0}
''';

-- load data as table
load jsonStr.`data` as datasource;

-- convert table as stream source
load mockStream.`datasource` options 
stepSizeRange="0-3"
as newkafkatable1;

-- aggregation 
select cast(key as string) as k,count(*) as c  from newkafkatable1 group by key
as table21;

-- output the the result to console.
-- save append table21  
-- as console.`` 
-- options mode="Complete"
-- and duration="10"
-- and checkpointLocation="/tmp/cpl3";

-- save the data to mysql.
save append table21  
as jdbc.`mysql1.test1` 
options mode="Complete"
and `driver-statement-0`="create table  if not exists test1(k TEXT,c BIGINT)"
and `statement-0`="insert into wow.test1(k,c) values(?,?)"
and duration="3"
and checkpointLocation="/streamingpro-test/kafka/test/mysql";
```
I just modify the connect url,user,password  and the checkpointLocation. And I already create a database named wow with utf8 encode.

The streamingpro version is 1.1.6, spark version is 2.4, mysql version is 8.0.13.

After running above script, I can get the job info by `/stream/jobs`.
And the below is the log file which is stored in Baidu Cloud Disk:

url：https://pan.baidu.com/s/1AtOPEkPeLp9qpDxtdFHZIg 
password：x60k

**Comment by 935205406** [comment]
I solved it by using the other way to create table instead of using `driver-statement-0` in save statement.
The detail in the following issue which I create:
https://github.com/allwefantasy/streamingpro/issues/906
