### ISSUE TITLE
[New Feature] Aliyun Deploy Support for MLSQL

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/byzer-lang#585]
MLSQL aims to make people easy to deploy and use it in data processing/machine learning. But it always has a lot of complex environmental problems our customers meet.

For people just want to spend several minutes to give it a try，it would be useful if  provide them an web console. In web console, our customers can request a new MLSQL instance and paste the example to the MLSQL editor then run it.

One possible architecture here would be like this: 

<img width="801" alt="wx20181014-115058 2x" src="https://user-images.githubusercontent.com/797758/46912414-80ab5400-cfa7-11e8-9281-10402f7ebde2.png">

When user A login and wants to try the mlsql, the web console will dynamically request an ECS instance from Aliyun and deploy MLSQL in the ECS. The user A should pay this instance according to
the time used. The default time should be an hour. 

All instances share the same OSS(HDFS), MLSQL will automatically create a home directory for every user and add home prefix for the path variables.  The web console will clean the OSS home directories which have already existed one hour.

If it'possible that we can dynamically create OSS storage for every user and release them after one hour, then we do not need to have the shared OSS.

According to the upper description, the key to supports Aliyun cloud is to develop a web console.
The web console is used by users directly so it should have:

1. User manager system
2. The right to operate Aliyun.

The tech we can use in web console would be React + Java Spring boot. Spring boot provides API and React provide the interactive pages. Hope that later people would create their own console with the  APIs provided by the spring boot application.

------------------------------------------------------------------------------------------------------

Notice 1:

We have two options, we can create MLSQL instance/OSS with the user A's Aliyun account or with the web console's Aliyun account.  The second way may be the best choice for now.

Notice 2:

The design of the web console should consider that we will at least support AWS/Aliyun.  We will support Aliyun first.

**Comment by RebieKong** [comment]
is there any doc about hdfs on oss?
