### ISSUE TITLE
java.sql.SQLException: Can't call commit when autocommit=true

### ISSUE THREAD

**Issue by iduanyingjie** [byzer-org/byzer-lang#586]
在代码streamingpro-spark-2.3.0-adaptor/src/main/java/org/apache/spark/sql/jdbc/UpsertUtils.scala的第125行 这里，如果supportsTransactions是false，不能直接conn.commit()

**Comment by allwefantasy** [comment]
Is there any problem ?
We will close this issue. You can reopen it or create a new one if you have any other questions.
