### ISSUE TITLE
XQL报错

### ISSUE THREAD

**Issue by Mvpanswer7** [byzer-org/byzer-lang#60]
照着例子连接了一个mysql，报错如下：
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:526)
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505)
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479)
com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:489)
com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:72)
com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:1606)
com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:633)
com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:347)
com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:219)
org.apache.spark.sql.execution.datasources.jdbc.DriverWrapper.connect(DriverWrapper.scala:45)
org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:61)
org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$createConnectionFactory$1.apply(JdbcUtils.scala:52)
org.apache.spark.sql.execution.datasources.jdbc.JDBCRDD$.resolveTable(JDBCRDD.scala:58)
org.apache.spark.sql.execution.datasources.jdbc.JDBCRelation.<init>(JDBCRelation.scala:113)
org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:47)
org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:306)
org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:146)
streaming.dsl.LoadAdaptor$$anonfun$parse$1.apply(LoadAdaptor.scala:34)
streaming.dsl.LoadAdaptor$$anonfun$parse$1.apply(LoadAdaptor.scala:14)
scala.collection.immutable.Range.foreach(Range.scala:160)
streaming.dsl.LoadAdaptor.parse(LoadAdaptor.scala:14)
...
换了hive之后，报错如下：
org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:217)
org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:114)
org.apache.spark.sql.execution.SparkSqlParser.parse(SparkSqlParser.scala:48)
org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parsePlan(ParseDriver.scala:68)
org.apache.spark.sql.SparkSession.sql(SparkSession.scala:623)
streaming.dsl.SelectAdaptor.parse(SelectAdaptor.scala:17)
streaming.dsl.ScriptSQLExecListener.exitSql(ScriptSQLExec.scala:76)
streaming.dsl.parser.DSLSQLParser$SqlContext.exitRule(DSLSQLParser.java:226)
org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
streaming.dsl.ScriptSQLExec$.parse(ScriptSQLExec.scala:54)
streaming.rest.RestController.script(RestController.scala:83)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:497)
net.csdn.modules.http.RestController.filter(RestController.java:139)
net.csdn.modules.http.RestController.dispatchRequest(RestController.java:99)
net.csdn.modules.http.HttpServer$DefaultHandler.handle(HttpServer.java:184)
org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
org.eclipse.jetty.server.Server.handle(Server.java:499)
org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
java.lang.Thread.run(Thread.java:745)

**Comment by allwefantasy** [comment]
是查詢問題麼？ 最近通過https://github.com/allwefantasy/streamingpro/pull/62 https://github.com/allwefantasy/streamingpro/pull/61  https://github.com/allwefantasy/streamingpro/pull/59 解決了一些問題。你更新最新代碼後，如果還有問題，可以再載這個Issue上喝我聯系。

**Comment by mvasr7** [comment]
额，上面那个问题是spark上的默认driver被设置成了6版本的，更换后确实还是有bug，不过更新了最新代码以后测试已经ok了

**Comment by Mvpanswer7** [comment]
弱弱问一句，spark sql如何做能做到es的支持？想像hive那样对es进行查询，比如show tables就能查询到es indices

**Comment by Mvpanswer7** [comment]
structured streaming不支持es写入咩？测试了一下好像是这样滴

**Comment by Mvpanswer7** [comment]
xql参数怎么传json，比如在es_query里，直接“肯定不行吧，\"的话解析会报错

**Comment by Mvpanswer7** [comment]
@allwefantasy

**Comment by mvasr7** [comment]
目前sparksql遇到一个蛋疼的问题，limit总是不生效，从大表查数据的时候，哪怕是limit1，spark总要把表都load到内存中去，然后取limit，因为数据多就算加了pushdown，数据还是很多，有没有什么办法能让limit1直接生效的

**Comment by mvasr7** [comment]
@allwefantasy

**Comment by mvasr7** [comment]
另外 新的 set语法求文档~
