### ISSUE TITLE
select语句列名之别名解析不正确

### ISSUE THREAD

**Issue by CoderOverflow** [byzer-org/byzer-lang#615]
疑似bug 如图：
![ss6xth14vxs z w2fcr_ v](https://user-images.githubusercontent.com/29338660/47690136-d9c1eb80-dc27-11e8-9e8d-da778fb090e2.png)

**Comment by allwefantasy** [comment]
It seems that using a table name as the column prefix will cause this problem. Please rename it.

We will close this issue. You can reopen it or create a new one if you have any other questions.
