### ISSUE TITLE
How to save result files in batchpredict case when we use pythonAlg 

### ISSUE THREAD

**Issue by CoderOverflow** [byzer-org/byzer-lang#616]
How to save result files in batchpredict case when we use pythonAlg 

For seeing the visualized result of prediction, I need to save the images rendered by matplotlib.

As I have save the result images to the temp model folder  successfully in train.py, could you help me add
this feature in predict phase when we run batchPredict.py?

**Comment by allwefantasy** [comment]
We will close this issue. You can reopen it or create a new one if you have any other questions.
