### ISSUE TITLE
libsvm格式转换

### ISSUE THREAD

**Issue by foreverjay** [byzer-org/byzer-lang#640]
mlsql算法的格式对libsvm兼容很好，我想问下dataframe怎么转换libsvm格式

**Comment by allwefantasy** [comment]
MLSQL only cares Vector(In Spark). That means libsvm will be loaded and convert to features(vector) and label in MLSQL.

**Comment by allwefantasy** [comment]
So you do not need to convert dataframe to libsvm format. We recommend you use parquet format.

**Comment by allwefantasy** [comment]
If there are no other questions, we will close this issue. You can reopen it again if you still have any question.
