### ISSUE TITLE
do_server_auth is removed in worker.py in the latest spark 2.3.2

### ISSUE THREAD

**Issue by CoderOverflow** [byzer-org/byzer-lang#642]
do_server_auth is removed from spark 2.3.2 [Detail](https://git1-us-west.apache.org/repos/asf?p=spark.git;a=commitdiff;h=fc1c4e7d) 

local_connect_and_auth in spark 2.3.2
![o3g99 ksh cypljyv8 c6r](https://user-images.githubusercontent.com/29338660/48239170-d6d5b080-e408-11e8-900a-35df072645d4.png)

do_server_auth in spark 2.3.1
![t arf290c_jivf2m _8y](https://user-images.githubusercontent.com/29338660/48240189-d8a17300-e40c-11e8-8c77-2e9d4a68b603.png)

do_server_auth in spark 2.2.2
![0b z sructb3 x3qiyux2](https://user-images.githubusercontent.com/29338660/48240007-1baf1680-e40c-11e8-9ba8-4748df2feb92.png)

there is no auth function in spark 2.2.1
![k d2c xmyu gb b9 du 4](https://user-images.githubusercontent.com/29338660/48240089-6fb9fb00-e40c-11e8-9624-c37457e0cdae.png)

It seems that in spark 2.2.2 and spark 2.3.1 the current do_server_auth is being used, 
but in newer version 2.3.2 and 2.4 this method is removed and start using local_connect_and_auth method. In I earlier version 2.2.1 there is no authorization.

This will cause the streamingpro predictAPI of pythonAlg running unsuccessfully
So to modify the default worker.py makes no sense to some extend

**Comment by allwefantasy** [comment]
You are right.  We have fixed this issue the lasted commit.

**Comment by allwefantasy** [comment]
Please try it again and if there are any problems, please let me know.
