### ISSUE TITLE
I have successfully started MLSQL server ,so what should i do if i want to write a stream script?

### ISSUE THREAD

**Issue by dukeshiny** [byzer-org/byzer-lang#661]
![Uploading image.png…]()

**Comment by allwefantasy** [comment]
Try to follow this steps:

1. visit GitHub main page : https://github.com/allwefantasy/streamingpro
2. Find more examples [on our user guide](https://github.com/allwefantasy/streamingpro/blob/master/docs/docv2/user-guide.md).
3. search `Stream` in new page and you will find [Example](https://github.com/allwefantasy/streamingpro/blob/master/docs/en/mlsql-stream.md)

**Comment by allwefantasy** [comment]
Notice that  it's difficult to infer schema in the stream, so if you want to expand value(binary) in Kafka , you should specify the schema with options.

For example:
```sql
-- convert table as stream source
load kafka.`pi-content-realtime-db` options 
`kafka.bootstrap.servers`="---"
and valueFormat="json"
and valueSchema="st(field(column1,string),field(column2,string),field(column3,string))"
as newkafkatable1;
```
For now, we support csv/json.
then you can use  like this:
```sql
select column1,column2,column3,kafkaValue from newkafkatable1 
as table21;
```

you can use `kafkaValue` to get original value. column1,column2 are extracted from kafkaValue automatically.

**Comment by allwefantasy** [comment]
If you have any problem, please comment in this issue.
If you create a Stream job successfully in MLSQL, please close this issue.

**Comment by dukeshiny** [comment]
> If you have any problem, please comment in this issue.
> If you create a Stream job successfully in MLSQL, please close this issue.
I have tried many times as following commands:
################################
load kafka.`pi-content-realtime-db` options 
`kafka.bootstrap.servers`="192.168.1.1:9092,192.168.1.2:9092,192.168.1.3:9092"
and valueFormat="json"
and `topics`="usertest"
and valueSchema="st(field(column1,string),field(column2,string),field(column3,string))"
as newkafkatable1;
################################
But there is one problem occurs as following:
streaming.core.strategy.platform.SparkStreamingRuntime cannot be cast to streaming.core.strategy.platform.SparkRuntime
Can you help me solve this problem ?Thank you !

**Comment by allwefantasy** [comment]
This exception may be caused by your startup script. Let us suppose you start MLSQL with script like following:

```
cd spark-2.2.0-bin-hadoop2.7/

./bin/spark-submit   --class streaming.core.StreamingApp \
--master local[*] \
--name sql-interactive \
--jars ansj_seg-5.1.6.jar,nlp-lang-1.7.8.jar \
streamingpro-mlsql-1.1.2.jar    \
-streaming.name sql-interactive    \
-streaming.job.file.path file:///tmp/query.json \
-streaming.platform spark   \
.....
```

I guess you did not add this line:  `-streaming.platform spark`

**Comment by dukeshiny** [comment]
> This exception may be caused by your startup script. Let us suppose you start MLSQL with script like following:
> 
> ```
> cd spark-2.2.0-bin-hadoop2.7/
> 
> ./bin/spark-submit   --class streaming.core.StreamingApp \
> --master local[*] \
> --name sql-interactive \
> --jars ansj_seg-5.1.6.jar,nlp-lang-1.7.8.jar \
> streamingpro-mlsql-1.1.2.jar    \
> -streaming.name sql-interactive    \
> -streaming.job.file.path file:///tmp/query.json \
> -streaming.platform spark   \
> .....
> ```
> I guess you did not add this line: `-streaming.platform spark`
######
I have modified -streaming.platform spark_streaming to -streaming.platform spark,But there is another problem occurs as following :
Queries with streaming sources must be executed with writeStream.start();;
kafka
#######
Pls have a look at this issue

**Comment by dukeshiny** [comment]
@allwefantasy  Hi,William When I submit streamingpro with yarn command,a problem occurs as following:
###command###
spark2-submit   --class streaming.core.StreamingApp --master yarn  --deploy-mode client --name sql-interactive --jars ansj_seg-5.1.6.jar,nlp-lang-1.7.8.jar streamingpro-mlsql-1.1.3.jar --keytab /data6/soft/streamingpro/hi.keytab   --principal hi@ESTER.ORG -streaming.name sql-interactive    -streaming.job.file.path hdfs://nameservice1/tmp/query.json -streaming.platform spark   -streaming.rest true   -streaming.driver.port 9003   -streaming.spark.service true -streaming.thrift false -streaming.enableHiveSupport true 
###problem###
18/11/14 19:53:04 INFO yarn.Client: Application report for application_1540881724592_0411 (state: ACCEPTED)
18/11/14 19:53:05 INFO yarn.Client: Application report for application_1540881724592_0411 (state: ACCEPTED)
18/11/14 19:53:06 INFO yarn.Client: Application report for application_1540881724592_0411 (state: ACCEPTED)
18/11/14 19:53:07 INFO yarn.Client: Application report for application_1540881724592_0411 (state: ACCEPTED)
18/11/14 19:53:08 INFO yarn.Client: Application report for application_1540881724592_0411 (state: ACCEPTED)
18/11/14 19:53:09 INFO yarn.Client: Application report for application_1540881724592_0411 (state: ACCEPTED)
18/11/14 19:53:10 INFO yarn.Client: Application report for application_1540881724592_0411 (state: ACCEPTED)
18/11/14 19:53:11 INFO yarn.Client: Application report for application_1540881724592_0411 (state: ACCEPTED)
18/11/14 19:53:12 INFO cluster.YarnClientSchedulerBackend: Add WebUI Filter. org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter, Map(PROXY_HOSTS -> 192.168.1.1,192.168.1.2, PROXY_URI_BASES -> http://192.168.1.1:8088/proxy/application_1540881724592_0411,http://192.168.1.2:8088/proxy/application_1540881724592_0411), /proxy/application_1540881724592_0411
18/11/14 19:53:12 INFO ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /jobs, /jobs/json, /jobs/job, /jobs/job/json, /stages, /stages/json, /stages/stage, /stages/stage/json, /stages/pool, /stages/pool/json, /storage, /storage/json, /storage/rdd, /storage/rdd/json, /environment, /environment/json, /executors, /executors/json, /executors/threadDump, /executors/threadDump/json, /static, /, /api, /jobs/job/kill, /stages/stage/kill.
18/11/14 19:53:12 INFO cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: ApplicationMaster registered as NettyRpcEndpointRef(spark-client://YarnAM)
18/11/14 19:53:12 INFO yarn.Client: Application report for application_1540881724592_0411 (state: RUNNING)
18/11/14 19:53:12 INFO yarn.Client: 
         client token: Token { kind: YARN_CLIENT_TOKEN, service:  }
         diagnostics: N/A
         ApplicationMaster host: 10.22.5.114
         ApplicationMaster RPC port: 0
         queue: root.users.hive
         start time: 1542196382547
         final status: UNDEFINED
         tracking URL: http://192.168.1.1:8088/proxy/application_1540881724592_0411/
         user: hive
18/11/14 19:53:12 INFO cluster.YarnClientSchedulerBackend: Application application_1540881724592_0411 has started running.
18/11/14 19:53:12 INFO util.Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 50930.
18/11/14 19:53:12 INFO netty.NettyBlockTransferService: Server created on cdh214.kobe.org:50930
18/11/14 19:53:12 INFO storage.BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
18/11/14 19:53:12 INFO storage.BlockManagerMaster: Registering BlockManager BlockManagerId(driver, cdh214.kobe.org, 50930, None)
18/11/14 19:53:12 INFO storage.BlockManagerMasterEndpoint: Registering block manager cdh214.kobe.org:50930 with 366.3 MB RAM, BlockManagerId(driver, cdh214.kobe.org, 50930, None)
18/11/14 19:53:12 INFO storage.BlockManagerMaster: Registered BlockManager BlockManagerId(driver, cdh214.kobe.org, 50930, None)
18/11/14 19:53:12 INFO storage.BlockManager: external shuffle service port = 7337
18/11/14 19:53:12 INFO storage.BlockManager: Initialized BlockManager: BlockManagerId(driver, cdh214.kobe.org, 50930, None)
18/11/14 19:53:13 INFO ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /metrics/json.
18/11/14 19:53:13 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@389a5022{/metrics/json,null,AVAILABLE,@Spark}
18/11/14 19:53:13 INFO scheduler.EventLoggingListener: Logging events to hdfs://nameservice1/user/spark/spark2ApplicationHistory/application_1540881724592_0411
18/11/14 19:53:13 INFO util.Utils: Using initial executors = 0, max of spark.dynamicAllocation.initialExecutors, spark.dynamicAllocation.minExecutors and spark.executor.instances
18/11/14 19:53:13 WARN lineage.LineageWriter: Lineage directory /var/log/spark2/lineage doesn't exist or is not writable. Lineage for this application will be disabled.
18/11/14 19:53:13 INFO util.Utils: Extension com.cloudera.spark.lineage.NavigatorAppListener not being initialized.
18/11/14 19:53:13 INFO cluster.YarnClientSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.8
18/11/14 19:53:13 INFO core.StreamingproJobManager: JobCanceller Timer  started with initialDelay=30 checkTimeInterval=5
18/11/14 19:53:13 INFO platform.SparkRuntime: ps enabled...
18/11/14 19:53:13 INFO platform.SparkRuntime: start PSDriverBackend
Exception in thread "main" java.lang.AbstractMethodError
        at org.apache.spark.internal.Logging$class.initializeLogIfNecessary(Logging.scala:99)
        at org.apache.spark.ps.cluster.PSDriverBackend.initializeLogIfNecessary(PSDriverBackend.scala:15)
        at org.apache.spark.internal.Logging$class.log(Logging.scala:46)
        at org.apache.spark.ps.cluster.PSDriverBackend.log(PSDriverBackend.scala:15)
        at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
        at org.apache.spark.ps.cluster.PSDriverBackend.logInfo(PSDriverBackend.scala:15)
        at org.apache.spark.ps.cluster.PSDriverBackend.createRpcEnv(PSDriverBackend.scala:30)
        at org.apache.spark.ps.cluster.PSDriverBackend.start(PSDriverBackend.scala:53)
        at streaming.core.strategy.platform.SparkRuntime.createRuntime(SparkRuntime.scala:115)
        at streaming.core.strategy.platform.SparkRuntime.<init>(SparkRuntime.scala:32)
        at streaming.core.strategy.platform.SparkRuntime$.getOrCreate(SparkRuntime.scala:207)
        at streaming.core.strategy.platform.SparkRuntime.getOrCreate(SparkRuntime.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at streaming.core.strategy.platform.PlatformManager$.createRuntimeByPlatform(PlatformManager.scala:179)
        at streaming.core.strategy.platform.PlatformManager$.getRuntime(PlatformManager.scala:193)
        at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:81)
        at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
        at streaming.core.StreamingApp.main(StreamingApp.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Please help me check it out ,thanks

**Comment by allwefantasy** [comment]
Please make sure the MLSQL is compiled with spark 2.2.x(it seems this is your spark runtime), Otherwise it maybe be a bug.

**Comment by dukeshiny** [comment]
> Please make sure the MLSQL is compiled with spark 2.2.x(it seems this is your spark runtime), Otherwise it maybe be a bug.

OK,I use spark 2.3.0 with cdh5.14.2 platform,is that mean MLSQL doesn't support spark 2.3.0?

**Comment by allwefantasy** [comment]
No, MLSQL supports spark 2.2.x, spark2.3.x,spark 2.4.x. We will test our tests with 2.2.0,2.3.2,2.4.0. You should make sure the spark version compiling MLSQL is the same with the spark version runs MLSQL.
