### ISSUE TITLE
java.lang.NoSuchMethodError throws when run spark-submit

### ISSUE THREAD

**Issue by zhangxiaoqiong** [byzer-org/byzer-lang#662]
在SPARK_HOME目录下提交上手命令：./bin/spark-submit --class streaming.core.StreamingApp --master yarn-cluster --name sql-interactive streamingpro-mlsql-1.1.3.jar -streaming.name sql-interactive -streaming.job.file.path file:///tmp/query.json -streaming.platform spark -streaming.rest true -streaming.driver.port 9003 -streaming.spark.service true -streaming.thrift false -streaming.enableHiveSupport true

报错：
18/11/14 09:59:20 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
at streaming.core.strategy.platform.PlatformManager$.platformNameMapping(PlatformManager.scala:213)
at streaming.core.strategy.platform.PlatformManager$.getRuntime(PlatformManager.scala:193)
at streaming.core.strategy.platform.PlatformManager.run(PlatformManager.scala:81)
at streaming.core.StreamingApp$.main(StreamingApp.scala:14)
at streaming.core.StreamingApp.main(StreamingApp.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:542)
18/11/14 09:59:20 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;)
18/11/14 09:59:30 ERROR yarn.ApplicationMaster: SparkContext did not initialize after waiting for 100000 ms. Please check earlier log output for errors. Failing the application.
18/11/14 09:59:30 INFO yarn.ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;)
18/11/14 09:59:30 INFO yarn.ApplicationMaster: Deleting staging directory .sparkStaging/application_1541142863920_0021
18/11/14 09:59:30 INFO util.ShutdownHookManager: Shutdown hook called

**Comment by allwefantasy** [comment]
It seems there are multi scala libraries in the classpath.  Please make sure that the Scala version used to compile `streamingpro-mlsql-1.1.3.jar`  is the same with  the spark runtime .

**Comment by zhangxiaoqiong** [comment]
> It seems there are multi scala libraries in the classpath. Please make sure that the Scala version used to compile `streamingpro-mlsql-1.1.3.jar` is the same with the spark runtime .

那我的spark版本1.6.0，scala版本2.10.5，需要按相同的版本再编译一下项目？

**Comment by allwefantasy** [comment]
Unfortunately, We have already given up to maintain MLSQL based on spark-1.6.x, this means we cannot guarantee it will work as expected.  

We strongly recommend you upgrade to Spark 2.x.x (MLSQL support Spark 2.2.x, 2.3.x,2.4.x) and Scala 2.11(Spark version > 2 requires this).

Notice that Yarn cluster support different spark versions run together so it may not block you upgrade.

**Comment by allwefantasy** [comment]
Also, when you use the default build tool e.g.  `/dev/make-distribution.sh` ,  the version is spark 2.3.x

**Comment by zhangxiaoqiong** [comment]
> Also, when you use the default build tool e.g. `/dev/make-distribution.sh` , the version is spark 2.3.x

非常感谢！现在可以运行了，是我的spark版本问题，现在换成2.3.0了。

**Comment by allwefantasy** [comment]
We will close this issue if you have any other questions please reopen it or create a new one.
