### ISSUE TITLE
Json configuration file support received from the HTTP request

### ISSUE THREAD

**Issue by young0512** [byzer-org/byzer-lang#664]
The startup script of MLSQL  contains configuration item：
-streaming.job.file.path  hdfs://xxx.json

The Configuration item read from HDFS file by default.

I want to dynamically update the file content, can support get json strings from the HTTP request？

**Comment by allwefantasy** [comment]
It's a good idea. Now we can support such kinds as following:

1. classpath://
2. hdfs://
3. file://
4. http:// or https://

Also, the config file should be optional. Empty config file makes none sense.

I will create PR later for this Issue.
