### ISSUE TITLE
SparkSessionCacheManager：Unable to clean up session

### ISSUE THREAD

**Issue by latincross** [byzer-org/byzer-lang#667]
The closeSession of SessionManager does not call the method, resulting in the SparkSessionCacheManager calling clear regularly and unable to clean session.

**Comment by allwefantasy** [comment]
The [PR668](https://github.com/allwefantasy/streamingpro/pull/668) may still cause some problems.
If a user executes a long time job, then we will not update the visit time. Once the one-hour limit is reached, the system will log out the user. This may cause some unexpected situations. @latincross

**Comment by latincross** [comment]
You're right. When sessions are cleaned up, the temporary tables and functions registered by sessions will not be available. I'll think about that.

**Comment by latincross** [comment]
When closeSession occurs, I checked to see if there was a job that the user was running. If not, I would clear it from the cache, or skip it. @allwefantasy
