### ISSUE TITLE
Create a  AliYun Image for MLSQL Testing

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/byzer-lang#679]
The Image is based on Ubuntu 16-64. 
The following software should be installed under the `webuser` account:

1.  Conda
2. /home/webuser/apps/spark 2.2/2.3/2.4
3. OpenJDK, notice that  we need JDK not JRE.
4. maven

Once Conda is installed, make sure there is a enviroment named  "mlsql" ready. 
the mlsql should contain:

1. oss2
2. aliyun-python-sdk-core-v3
3. aliyun-python-sdk-ecs

This Image will be used in ECS instances created by scripts.

The scripts will send a shell script to the ECS instance which will do the following jobs:

1.  download MLSQL releases  from oss2 to `/home/webuser/apps/mlsql-test` directory.
2. start MLSQL server 
3. post mslql script to the server and check the result.

**Comment by RebieKong** [comment]
Image in aliyun had been create, something had been changed.
I had create 2 enviroments, one named mlsql-2.7 that python version is 2.7, another is mlsql-3.5 that python version is 3.5.
Both of then had install that packages you specify

**Comment by allwefantasy** [comment]
Awesome! @RebieKong

**Comment by RebieKong** [comment]
if anyone want to have a choice,you can comment you aliyun uid under this issue,i will share it to you
