### ISSUE TITLE
How to do ETL from Kafka in MLSQL

### ISSUE THREAD

**Issue by yooo1007** [byzer-org/byzer-lang#684]
你好，我研究Streamingpro有一个星期了，kafka的传输的value是json格式，我的目的是传输的json数据进行过滤保留某些字段，并对某些字段进行判断，不合格的舍弃。不知道是我没融汇贯通还是现阶段streamingpro支持不了该功能。

**Comment by allwefantasy** [comment]
Do you have looked in this [document](https://github.com/allwefantasy/streamingpro/blob/master/docs/en/mlsql-stream.md) or [this one](https://github.com/allwefantasy/streamingpro/blob/master/docs/mlsql-stream.md)?

I guess what you want is like this:

```sql 
load kafka.`pi-content-realtime-db` options
`kafka.bootstrap.servers`="---"
and `subscribe`="---"
and valueFormat="json"
and valueSchema="st(field(column1,string),field(column2,string),field(column3,string))"
as kafka_post_parquet;
```

the valueFormat specify what's the format of data stored in Kafka and the valueSchema specify what's the schema. We also will return the kafkaValue which is the original Json value. you can use it illustrated as following:

```sql
select column1,column2,column3,kafkaValue from kafka_post_parquet 
as table21;
```

```
st(field(column1,string),field(column2,string),field(column3,string))
``` 

is used to describe your schema. If you are familiar with Spark StructType, you will find they are really close. st equal to StructType, field equal to StructField, string equal to StringType. Following datatypes are supported now:

```
st
field
string
float
double
integer
short
date
binary
map
array
```
For example, you can use map like this:

```
st(field(column1,map(string,string)))
```

Or be more complicated:

```
st(field(column1,map(string,array(st(field(columnx,string))))))
```

Hope this helps.

**Comment by allwefantasy** [comment]
We will close this issue if you have any questions please reopen it
