### ISSUE TITLE
Abnormal exit from application mode

### ISSUE THREAD

**Issue by latincross** [byzer-org/byzer-lang#685]
Because the dispatch method of StrategyDispatcher does not throw the captured exception outward, the call chain exception causes the program to be stuck, and the transition code of the program abnormal exit and return is zero, which should be non-zero.

**Comment by allwefantasy** [comment]
Yes, this is a bug when it runs in application mode.

**Comment by allwefantasy** [comment]
It is also addressed in #86. Realy an old issue.....
