### ISSUE TITLE
Included Carbondata version is too low

### ISSUE THREAD

**Issue by RebieKong** [byzer-org/byzer-lang#686]
The latest carbondata version is 1.5, supporting SPARK 2.3.2.
But StreamingPro includes Carbondata 1.3.1, which does not support sparks 2.2 +.
This means that we can only use spark 2.2.
If we can upgrade it?

**Comment by allwefantasy** [comment]
We still do not have time to maintain the integration with CarbonData since we integrated it before. 
 I am considering maybe we should give up the integration with CarbonData for now.

**Comment by RebieKong** [comment]
I agree,maybe remove is good because it doesn't works well currently

**Comment by allwefantasy** [comment]
I will try to make it work in MLSQL-1.1.5 and make CarbonData as the storage of stream engine. CarbonData will be included in MLSQL by default.

**Comment by RebieKong** [comment]
grate~ @allwefantasy

**Comment by RebieKong** [comment]
@allwefantasy it is not ok to use carbondata in spark 2.4 because carbondata do not support,there will be some unknow problem.
let's update this doc page.
https://github.com/allwefantasy/streamingpro/blob/master/docs/docv2/getting_started/installation.md

**Comment by allwefantasy** [comment]
If you enable carbondata in spark 2.4 then mlsql will give you a warning message and it will take no effect.

**Comment by allwefantasy** [comment]
But of course, you can provide a PR to make this clear in doc.

**Comment by allwefantasy** [comment]
We will close this issue if you do not have other questions.  If need ,please reopose this issue.

**Comment by RebieKong** [comment]
I will provide a PR，later
