### ISSUE TITLE
MLSQL connect Kafka error

### ISSUE THREAD

**Issue by zhangxiaoqiong** [byzer-org/byzer-lang#688]
我向接口run/script，post提交sql:
load kafka9.`hello`  options `kafka.bootstrap.servers`="cdh1:9092"
and `topics`="zxq_topic"
as newkafkatable1;
时报错，请问是什么原因？
![image](https://user-images.githubusercontent.com/16643547/48761226-18a50780-ece3-11e8-9164-66e89801613e.png)

**Comment by allwefantasy** [comment]
MLSQL Streaming always need you to save the final result.  Because the save will trigger the stream to run.

**Comment by allwefantasy** [comment]
Try add this:

```sql
save append newkafkatable1  
as console.`` 
options mode="Append"
and duration="10"
and checkpointLocation="/tmp/cpl3";

```

**Comment by zhangxiaoqiong** [comment]
> Try add this:
> 
> ```sql
> save append newkafkatable1  
> as console.`` 
> options mode="Append"
> and duration="10"
> and checkpointLocation="/tmp/cpl3";
> ```

增加这行语句后又有报错：
![image](https://user-images.githubusercontent.com/16643547/48768631-86a5fa80-ecf4-11e8-8b2b-7624d6c30d94.png)

我的kafka topic中的数据如下：
{"key":0,"value":"value0"}
{"key":1,"value":"value1"}
{"key":2,"value":"value2"}
{"key":3,"value":"value3"}

**Comment by allwefantasy** [comment]
What's you kafka version?

**Comment by zhangxiaoqiong** [comment]
> What's you kafka version?

0.9，1.0都用了

**Comment by allwefantasy** [comment]
Not Kafka client,  I mean the version of your Kafka server.
