### ISSUE TITLE
[Duplicate with #685] 运行spark批处理任务过程中如果发生异常spark状态仍然是成功

### ISSUE THREAD

**Issue by moranrr** [byzer-org/byzer-lang#695]
任务提交到yarn运行，状态显示成功，其实是发生了异常退出。比如读写关系型数据库的l时候网络不通，或者sql有问题。

**Comment by allwefantasy** [comment]
#685 We wil fix this issue in MLSQL-1.1.5 . It will be released next week.

**Comment by allwefantasy** [comment]
Also, we recommend you to use `batch.mlsql` module.

**Comment by mvasr7** [comment]
能否顺便把报错信息也优化一下，现在很多任务的报错信息只有一个job aborted

**Comment by allwefantasy** [comment]
We will close this issue and continue to talk about this issue in #685.  Also it seems we will delay fixing this in MLSQL-1.1.6
