### ISSUE TITLE
How to run MLSQL in  application mode instead of service mode

### ISSUE THREAD

**Issue by foreverjay** [byzer-org/byzer-lang#697]
下面的方式支持json，mlsql如何这样运行呢？

spark-submit --class streaming.core.StreamingApp \
--jars mysql-connector-java-5.1.44-bin.jar,ansj_seg-5.1.6.jar,nlp-lang-1.7.7.jar \
--master local[2] \
--name xxx \
streamingpro-mlsql-1.1.3.jar  \
-streaming.platform spark \
-streaming.name xxxx -streaming.job.file.path /tmp/sql.json

**Comment by allwefantasy** [comment]
You can use `batch.mlsql` module in /tmp/sql.json. For example:

```json
{
  "mlsql": {
    "desc": "测试",
    "strategy": "spark",
    "algorithm": [],
    "ref": [],
    "compositor": [
      {
        "name": "batch.mlsql",
        "params": [
          {
            "sql": [
              "select 'a' as a as table1;",
              "save overwrite table1 as parquet.`/tmp/kk`;"
            ]
          }
        ]
      }
    ],
    "configParams": {
    }
  }
}
```

**Comment by foreverjay** [comment]
> You can use `batch.mlsql` module in /tmp/sql.json. For example:
> 
> ```json
> {
>   "mlsql": {
>     "desc": "测试",
>     "strategy": "spark",
>     "algorithm": [],
>     "ref": [],
>     "compositor": [
>       {
>         "name": "batch.mlsql",
>         "params": [
>           {
>             "sql": [
>               "select 'a' as a as table1;",
>               "save overwrite table1 as parquet.`/tmp/kk`;"
>             ]
>           }
>         ]
>       }
>     ],
>     "configParams": {
>     }
>   }
> }
> ```

thank you very much!!!
