### ISSUE TITLE
map reducer

### ISSUE THREAD

**Issue by ww102111** [byzer-org/byzer-lang#7]
工程是否允许map reduce的操作工作批处理呢。

**Comment by allwefantasy** [comment]
没明白你睡的啥意思……

**Comment by allwefantasy** [comment]
没明白你说的意思……

**Comment by ww102111** [comment]
您好，我编译build还是有问题，怎么办。

**Comment by allwefantasy** [comment]
建议不要编译了。直接使用编译好的版本。在项目readme中有下载地址

**Comment by ww102111** [comment]
好的，不过我想可不可以把SQL的数据处理部门改写streaming数据处理的部分可以更好的举例说的更详细不。我没看太懂sql类比streaming数据处理的这部分。

**Comment by allwefantasy** [comment]
流式计算例子参考：  http://www.jianshu.com/p/d10edd6c7cf9
