### ISSUE TITLE
 How to use partition with MLSQL save operation

### ISSUE THREAD

**Issue by zhangsancode** [byzer-org/byzer-lang#700]
for example:
select 1 as a,'jack' as b as bbc;

save overwrite bbc as parquet.`/tmp/hello`;

I want the number of file is ten

**Comment by zhangsancode** [comment]
I think a resolution: you can use  set operation before save
set spark.sql.shuffle.partitions=10 options type="conf";

**Comment by allwefantasy** [comment]
save overwrite bbc as parquet./tmp/hello where fileNum=“10”;

**Comment by allwefantasy** [comment]
save overwrite bbc as parquet./tmp/hello where fileNum=“10”;

**Comment by zhangsancode** [comment]
thanks~

**Comment by allwefantasy** [comment]
Load also supports fileNum parameter

**Comment by allwefantasy** [comment]
Load also supports fileNum parameter
