### ISSUE TITLE
How to use na fill in mlsql?

### ISSUE THREAD

**Issue by zhangsancode** [byzer-org/byzer-lang#701]
In spark, we can user df.na.fill to handle null, but in mlsql you can't call na.fill, i wan't to realize sqlalg  to offer  na.fill semantic。

**Comment by zhangsancode** [comment]
I have find the doc about how to write my sqlalg https://github.com/allwefantasy/streamingpro/blob/master/docs/docv2/contribute/estimator-transformer-in-mlsql.md

**Comment by zhangsancode** [comment]
Now, the doc don't said how to run with myself  na jar, is use register ?

**Comment by allwefantasy** [comment]
Make sure the package name is "streaming.dsl.mmlib.algs" and the class name starts with SQL and ends with Ext. Then the system will find it automatically.

**Comment by allwefantasy** [comment]
`streaming.dsl.mmlib.algs.SQLCacheExt` is a transformer used to cache dataframe, take his for example.

**Comment by RebieKong** [comment]
I think na fill is not a simple sql action,it is a collection action. We may need to think more clear how to do this type of action.
Let's see this action will effect all column but not one
maybe some kind of action like train may look goods.
but keyword train may not fit to this.
should we add a keyword like transform.

**Comment by allwefantasy** [comment]
@RebieKong You are right, Transformer is good for this. The keyword train is used by estimator which will generate a model after data processing. keyword run is ok and MLSQL already supports this keyword.

**Comment by zhangsancode** [comment]
I code a Transformer


```
package streaming.dsl.mmlib.algs

import org.apache.spark.ml.param.Param
import org.apache.spark.sql.{DataFrame, SparkSession}
import org.apache.spark.sql.expressions.UserDefinedFunction
import streaming.dsl.mmlib.SQLAlg
import streaming.dsl.mmlib.algs.param.{BaseParams, WowParams}
import streaming.session.MLSQLException

class SQLNaExt(override val uid: String) extends SQLAlg with WowParams {

  override def train(df: DataFrame, path: String, params: Map[String, String]): DataFrame = {

    val exe = params.get(execute.name)

    if (!execute.isValid(exe)) {
      throw new MLSQLException(s"${execute.name} should be fill or drop or replace")
    }

    if (exe == "fill") {
      df.na.fill("")
    } else if (exe == "drop") {
      df.na.drop()
    } else if(exe == "replace") {
      //df.na.replace()
    }

    df
  }

  override def load(sparkSession: SparkSession, path: String, params: Map[String, String]): Any = {
    throw new RuntimeException("train is not support")
  }

  override def predict(sparkSession: SparkSession, _model: Any, name: String, params: Map[String, String]): UserDefinedFunction = {
    null
  }

  final val execute: Param[String] = new Param[String](this, "execute", "fill|drop|replace", isValid = (m: String) => {
    m == "fill" || m == "drop" || m == "replace"
  })

  def this() = this(BaseParams.randomUID())
}


```
and I have submit mlsql with -jars, now How i use the Transformer? For example,

```

include hdfs.`/tmp/virtual_tables/community_stream`;

select
 *
from community_stream as write_table ;

```

**Comment by allwefantasy** [comment]
Rename you transformer to SQLNaFillExt . Then you can use like this:

```
run data as NaFillExt.`` where execute="fill";
```

**Comment by RebieKong** [comment]
greate, if we can remove ``` `` ``` to make this script looks much better

**Comment by RebieKong** [comment]
> Rename you transformer to SQLNaFillExt . Then you can use like this:
> 
> ```
> run data as NaFillExt.`` where execute="fill";
> ```

should we add a transformer that can run some scala code like  
```run data as ScalaDF.`` where execute="na().fill()" ``` 
?
