### ISSUE TITLE
Some files maybe not in their places

### ISSUE THREAD

**Issue by RebieKong** [byzer-org/byzer-lang#711]
1. https://github.com/allwefantasy/streamingpro/tree/master/src/main/java/streaming/util
2. https://github.com/allwefantasy/streamingpro/tree/master/template/rest
3. https://github.com/allwefantasy/streamingpro/tree/master/bin
4. https://github.com/allwefantasy/streamingpro/tree/master/images
if we need to do something to codes in upper links.

**Comment by allwefantasy** [comment]
Sorry, I dot get the point.

**Comment by RebieKong** [comment]
1. if this code still using?
2. if it is belong to some module, I think we need to put they in place
3. the images is working for docs. let 's move they into the docs dir~
