### ISSUE TITLE
Use allPathPrefix is invalid 

### ISSUE THREAD

**Issue by zhangsancode** [byzer-org/byzer-lang#715]
I want user 
http://abc.com/run/script?
sql=include hdfs.`init_tables11/init_user_info`;
select * from init_user_info limit 100 as outtt;&
owner=myname&
jobName=12ejsahjkfdjkashkfhdkwahekdjkasbd&
allPathPrefix={"myname":"/user/"}

but http response 
Input path does not exist: hdfs://nameservice1/user/hdfs/init_tables11/init_user_info

I want the mlsql find /user/myname/init_tables11/init_user_info

**Comment by allwefantasy** [comment]
try this:  

```sql
include hdfs.`$HOME/init_tables11/init_user_info`;
```

**Comment by allwefantasy** [comment]
We will close this issue, if there are any other problems, please address a new issue or reopen this one.
