### ISSUE TITLE
use python script  error

### ISSUE THREAD

**Issue by zhangsancode** [byzer-org/byzer-lang#717]
```
-- using set statement to hold your python script
-- Notice that the first parameter of function you defined should be self.  
set echoFun='''
import json
def apply(self,m):
    x = json.loads(m)
    return x.get('b', '555')
    
''';

-- load script as a table, every thing in mlsql should be table which 
-- can be processed more conveniently.
load script.`echoFun` as scriptTable;

-- register `apply` as UDF named `echoFun` 
register ScriptUDF.`scriptTable` as echoFun options
-- specify which script you choose
and lang="python"
-- As we know python is not strongly typed language, so 
-- we should manually spcify the return type.
-- map(string,string) means a map with key is string type,value also is string type.
-- array(string) means a array with string type element.
-- nested is support e.g. array(array(map(string,array(string))))
and dataType="string"
;

-- create a data table.
set data='''
{"a":{'b':'3'}}
{"a":{'b':'3'}}
{"a":{'b':'3'}}
{"a":{'b':'3'}}
''';
load jsonStr.`data` as dataTable;

select * from dataTable as outtt;
-- using echoFun in SQL.
--select echoFun(a) as res from dataTable as output;
```

Error info is 

18/11/28 20:41:56 ERROR udf.PythonSourceUDF: [owner] [admin] java.lang.RuntimeException: org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema can not been converted to python object
[owner] [admin] streaming.jython.JythonUtils.toPy(JythonUtils.java:114)
[owner] [admin] streaming.udf.PythonSourceUDF$$anon$2$$anonfun$apply$4.apply(PythonSourceUDF.scala:97)
[owner] [admin] streaming.udf.PythonSourceUDF$$anonfun$5.apply(PythonSourceUDF.scala:73)
[owner] [admin] streaming.udf.PythonSourceUDF$$anonfun$5.apply(PythonSourceUDF.scala:70)
[owner] [admin] streaming.udf.PythonSourceUDF$$anon$2.apply(PythonSourceUDF.scala:96)
[owner] [admin] org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
[owner] [admin] org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
[owner] [admin] org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
[owner] [admin] scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:389)
[owner] [admin] scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
[owner] [admin] org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
[owner] [admin] org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
[owner] [admin] org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
[owner] [admin] org.apache.spark.scheduler.Task.run(Task.scala:109)
[owner] [admin] org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
[owner] [admin] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[owner] [admin] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[owner] [admin] java.lang.Thread.run(Thread.java:748)
18/11/28 20:41:56 ERROR executor.Executor: Exception in task 0.0 in stage 175.0 (TID 2891)
org.apache.spark.SparkException: Failed to execute user defined function(anon$2: (struct<b:string>) => string)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema can not been converted to python object
	at streaming.jython.JythonUtils.toPy(JythonUtils.java:114)
	at streaming.udf.PythonSourceUDF$$anon$2$$anonfun$apply$4.apply(PythonSourceUDF.scala:97)
	at streaming.udf.PythonSourceUDF$$anonfun$5.apply(PythonSourceUDF.scala:73)
	at streaming.udf.PythonSourceUDF$$anonfun$5.apply(PythonSourceUDF.scala:70)
	at streaming.udf.PythonSourceUDF$$anon$2.apply(PythonSourceUDF.scala:96)
	... 13 more
18/11/28 20:41:56 INFO executor.CoarseGrainedExecutorBackend: Got assigned task 2892
18/11/28 20:41:56 INFO executor.Executor: Executor is trying to kill task 1.0 in stage 175.0 (TID 2892), reason: Stage cancelled
18/11/28 20:41:56 INFO executor.Executor: Running task 1.0 in stage 175.0 (TID 2892)
18/11/28 20:41:56 INFO executor.Executor: Executor killed task 1.0 in stage 175.0 (TID 2892), reason: Stage cancelled

**Comment by allwefantasy** [comment]
It seems to work properly.

Here is my environment:
1. MLSQL-1.1.5
2. Spark 2.3.2

<img width="617" alt="wx20181129-162208 2x" src="https://user-images.githubusercontent.com/797758/49208528-f605a380-f3f2-11e8-962e-29598af76d6b.png">

**Comment by zhangsancode** [comment]
oh, i write wrong, Can you test 
`select echoFun(a) as res from dataTable as output;`

**Comment by allwefantasy** [comment]
This is because column a is a struct type (Row) but not a string.   try this code:

```sql
set echoFun='''
def apply(self,m):
    #please put import in the function body
    import json
    x = json.loads(m)
    return x.get('b', '555')
''';

load script.`echoFun` as scriptTable;


register ScriptUDF.`scriptTable` as echoFun options
lang="python"
and dataType="string"
;

set data='''
{"a":{'b':'3'}}
{"a":{'b':'3'}}
{"a":{'b':'3'}}
{"a":{'b':'3'}}
''';
load jsonStr.`data` as dataTable;
select echoFun(to_json(a)) as res from dataTable as output;
```

**Comment by allwefantasy** [comment]
Also you can simplify this script like this:

```sql

register ScriptUDF.`` as echoFun where lang="python"
and dataType="string"
and code='''
def apply(self,m):
    #please put import in the function body
    import json
    x = json.loads(m)
    return x.get('b', '555')
'''
;

set data='''
{"a":{'b':'3'}}
{"a":{'b':'3'}}
{"a":{'b':'3'}}
{"a":{'b':'3'}}
''';
load jsonStr.`data` as dataTable;
select echoFun(to_json(a)) as res from dataTable as output;
```

**Comment by zhangsancode** [comment]
Thanks, it has work
