### ISSUE TITLE
Providing MLSQL Query Proxy Application

### ISSUE THREAD

**Issue by allwefantasy** [byzer-org/byzer-lang#742]
In many cases, we will deploy multi MLSQL instances as load balance. this means we should know which one is idle(or  the one who have most free cores available) and then request that one. Also when the system is not busy, we may reduce the number of instances and vice versa. 

The best way to implement this is to provide an MLSQL proxy,  and the instances will report related resources information to the proxy. MLSQL should support reporting to multi proxy instances.

**Comment by cfmcgrady** [comment]
Maybe a batter idea is put Query Proxy into the MLSQL client side.

**Comment by RebieKong** [comment]
is it good to mark as 1.1.6?
