### ISSUE TITLE
谢谢，问题解决了，是spark安装没有加hive服务！

### ISSUE THREAD

**Issue by BigAlanSun** [byzer-org/byzer-lang#763]
_Originally posted by @Tom-YJ in https://github.com/allwefantasy/streamingpro/issues/292#issuecomment-399347756_
兄弟，有没有具体使用的说明啊，求帮助，万分感谢！！！

**Comment by allwefantasy** [comment]
Can you describe the problem you have meet?

**Comment by BigAlanSun** [comment]
Thanks for your Email.

This's my select code.

connect jdbc where driver="org.apache.hive.jdbc.HiveDriver"
and url="jdbc:hive2://192.168.0.83:10000/default"
and user="hdfs" and password="hdfs"  as default1;
​
load jdbc.`default1.books` as books;
​
select * from books as books;

This's my start streamingPro shell.

[cid:image003.png@01D4920D.71338920][cid:image005.png@01D4920D.71338920]

this's the start log

[cid:image003.png@01D4920D.71338920][cid:image009.png@01D4920D.71338920]

but run the select code nothing to return on web ui.

[cid:image003.png@01D4920D.71338920][cid:image011.png@01D4920D.71338920]

[cid:image003.png@01D4920D.71338920][cid:image015.png@01D4920D.71338920]

run sql log

[cid:image003.png@01D4920D.71338920][cid:image016.png@01D4920D.71338920]


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: WilliamZhu <notifications@github.com>
发送时间: Wednesday, December 12, 2018 10:54:31 AM
收件人: allwefantasy/streamingpro
抄送: alan sun; Author
主题: Re: [allwefantasy/streamingpro] 谢谢，问题解决了，是spark安装没有加hive服务！ (#763)


Can you describe the problem you have meet?

**Comment by allwefantasy** [comment]
You do not need load hive like that. Please make sure the hive.xml is configured in your environment. Then you can use sentence like that:

```
load hive.`db.table` as newtable;
select * from newtable;

-- or 

select * from db.table as new table;
```

Do not remember to set `-streaming.enableHiveSupport true` when start MLSQL.

**Comment by BigAlanSun** [comment]
Thanks. Support jdbc connection hive？

**Comment by allwefantasy** [comment]
No. JDBC  only supports DBS e.g. MySQL

**Comment by BigAlanSun** [comment]
thanks. I have solved it.You can close this issue.

**Comment by allwefantasy** [comment]
JDBC should supports hive. We will try.

**Comment by allwefantasy** [comment]
> No. JDBC only supports DBS e.g. MySQL

This is wrong.

**Comment by allwefantasy** [comment]
Add batchsize to where conditions:

```sql
connect jdbc where driver="org.apache.hive.jdbc.HiveDriver" 
and url="jdbc:hive2://192.168.0.83:10000/default" 
and user="hdfs" and password="hdfs" and fetchsize="100" as default1; 
​ 
load jdbc.`default1.books` as books;
```
