### ISSUE TITLE
[BUG] as keyword report an error

### ISSUE THREAD

**Issue by zhangsancode** [byzer-org/byzer-lang#769]
if  " as " keyword is upper, mlsql report error

select 1 as a,'jack' as b AS bbc;

extraneous input 'AS' expecting {<EOF>, ',', 'FROM', 'WHERE', 'GROUP', 'ORDER', 'HAVING', 'LIMIT', 'LATERAL', 'WINDOW', 'UNION', 'EXCEPT', 'MINUS', 'INTERSECT', 'SORT', 'CLUSTER', 'DISTRIBUTE'}(line 1, pos 26)

== SQL ==
select 1 as a,'jack' as b AS bbc
--------------------------^^^

**Comment by allwefantasy** [comment]
We will fix this later.
