### ISSUE TITLE
spark log报error但是yarn给出的finalStatus是SUCCEEDED

### ISSUE THREAD

**Issue by Mvpanswer7** [byzer-org/byzer-lang#86]
许多类似的地方，举例 MultiSQLSourceCompositor.scala：
        val df = session.read.format(sourceConfig("format").toString).options((_cfg - "format" - "path" -"outputTable").map(f => (f._1.toString, f._2.toString))).load(sourcePath)

这里出现异常的话，最后会在serviceframework的dispath函数里捕获，但是只打印了错误信息，没有结束spark程序，导致出现spark log报error但是yarn给出的finalStatus是SUCCEEDED，你可以测试一下。

**Comment by allwefantasy** [comment]
We need to throw a specific exception to make yarn knows that and mark the finalStatus is FAIL.

**Comment by allwefantasy** [comment]
This issue will not fix
