### ISSUE TITLE
sparksql方式如何添加udf函数

### ISSUE THREAD

**Issue by Mvpanswer7** [byzer-org/byzer-lang#88]
在sparkRuntime中注册了ufd之后，通过sparksql的http接口，即/run/sql，可以使用注册的udf函数；但是通过sparksql开启的thriftserver，即通过jdbc:hive2:访问时，就无法使用udf函数，报错显示未注册在default数据库中，这个怎么破？

**Comment by allwefantasy** [comment]
thriftserver使用的自己的spark session。
