### ISSUE TITLE
请教您个关于spark stream on Mongodb的问题

### ISSUE THREAD

**Issue by infcnwangjie** [byzer-org/byzer-lang#9]
最近看到您用Scala写了些关于spark stream 的demo，对我写spark streaming on mongo有很多指导价值，在这里我对spark streaming on monggo 有些迷茫，不知道怎么才能将spark  通过stream与mongo 很好的结合起来？请前辈赐教

**Comment by allwefantasy** [comment]
MongoDB 官方就提供了 Hadoop-Mongoldb connector项目。里面包含了 spark 和 mongoldb的集成。你直接使用就好。

**Comment by rorovic** [comment]
自己很早之前在使用Hadoop-Mongoldb connector的时候有过一些教训 仅供参考 @infcnwangjie   http://blog.csdn.net/djy572568633/article/details/46654857  注意权限
