### ISSUE TITLE
`driver-statement-0` is not effective in save statement when sink is mysql.

### ISSUE THREAD

**Issue by 935205406** [byzer-org/byzer-lang#906]
With Streamingpro version 1.1.6,  Spark version 2.4 and mysql version 8.0.13.
The below script is not effective:

```
-- omit load data from kafka and connet to mysql and business process
save append resultDataTable  
as jdbc.`mysql1.test1` 
options mode="Complete"
and `driver-statement-0`="create table  if not exists test1(k TEXT,c BIGINT)"
and `statement-0`="insert into wow.test1(k,c) values(?,?)"
and duration="3"
and checkpointLocation="/streamingpro-test/kafka/test/mysql";
```
In this way, I can create `test1` table, but I can't insert data to table;

however, when I use the other way to create table, It works! Show as below:
```
-- omit load data from kafka and connet to mysql and business process

-- 创建表 用于存储结果 create table to store result
select 1 as a as FAKE_TABLE;
run FAKE_TABLE as JDBC.`mysql1` where 
`driver-statement-0`="create table  if not exists test1(k TEXT,c BIGINT)";

-- sink to mysql
save append resultDataTable  
as jdbc.`mysql1.test1` 
options mode="Complete"
and `statement-0`="insert into wow.test1(k,c) values(?,?)"
and duration="3"
and checkpointLocation="/streamingpro-test/kafka/test/mysql";

-- create table

```

Is this a bug to fix?

**Comment by allwefantasy** [comment]
I will try to repeat this problem.

**Comment by allwefantasy** [comment]
I am sure this is a bug. We will fix it in v1.1.7.1.  For now ,you can walk around this issue with your second way.

**Comment by allwefantasy** [comment]
The executor will get the wrong statement if you configure both driver and executor statement.

**Comment by allwefantasy** [comment]
We have fix this bug in PR-907. Thanks for your reported Issue.

**Comment by 935205406** [comment]
Still can't insert date into table by useing the latest version 1.1.7.1. Spark version 2.4 and mysql version 8.0.13.

Script and log are in Baidu Cloud Disk:

script:
https://pan.baidu.com/s/17armJtRrN9cq2e4m0-JPcw
password:39ad

log:
https://pan.baidu.com/s/1d4n6Xs5096xH7d0HRYEqOw 
passwork:wu97

It seems there is no obvious error or warn info.

**Comment by 935205406** [comment]
I solve it!
The script should modify to below:
```sql
save append table21  
as jdbc.`mysql1.test1` 
options mode="Complete"
and `driver-statement-0`="create table  if not exists test1(k TEXT,c BIGINT)"
-- instead of `statement-0` in doc `http://docs.mlsql.tech/zh/stream/datasource.html`
and `statement-1`="insert into wow.test1(k,c) values(?,?)" 
and duration="3"
and checkpointLocation="/streamingpro-test/kafka/test/mysql";
```
the `statement-0` in [doc](http://docs.mlsql.tech/zh/stream/datasource.html) should change to `statement-1`
