### ISSUE TITLE
Discuss(讨论):How to optimize this script?(如何优化这个脚本?)

### ISSUE THREAD

**Issue by 935205406** [byzer-org/byzer-lang#919]
I had created a streaming job to simply count every day. I mock some patient info to kafka, patient has below fields:
我新建了一个流任务，统计每天的总数。我造了一些 patient 信息到kafka， patient 的结构如下：
- name,string
- age,integer
- addr,string (means the province the patient from)
- arriveTime,long (timestamp in miliseconds) 

And I  cast arriveTime to date, then I  group patient info by addr and date. Finally I use `update` mode to write to Mysql Sink. When the date and addr not exist in mysql table, I insert the row, and when it exists, I update the count result.
我把arriveTime转为了date类型，并且根据addr与date进行group by操作。最终使用 `update` 模式来将结果写入Mysql。我的设想是，当最新的统计结果的addr与date在Mysql中不存在时，我执行insert插入操作，当存在时，我执行update更新操作。
It sounds simple. However I have some question when I wirite `save` statement.
这听起来很简单也很合理。但是我在最后写`save`语句时，遇到了问题。
 I use mysql sink and update mode to store result date, the `save` statement need `statement-[num]` to decide the behaviour. But I can't decide how to write it.
因为我使用mysql以及update模式存储结果，用`save`语句时会要求我必须要写 `statement-[num]` 语句，这个语句会在每次写入数据库时都执行，并且按照[num]的顺序执行。但是我不知道该如何写才能实现我上面的设想。

The first solution shows as below:
我一开始的解决方案如下：
```sql
save append resTable  
as jdbc.`mydb.test1` 
options mode="update"
and `statement-0`="delete from test1 where dt=?"
and `statement-1`="insert into test1(dt,addr,num) values(?,?,?)"
and duration="10"
and checkpointLocation="/streamingpro-test/kafka/patient/mysql/update";
```
I delete first whether the date and addr exists, and then I use `insert` to add data.
不管addr,date存不存在，我先删除，然后在插入计算结果。
This solved my problem, however when the table is large enough, query table will slow.
这样确实解决了问题，但是过多的删除会导致mysql产生许多碎片，当数据多了之后，查询会很慢。

Then, below is my second solution(all script):
下面，是我的第二种方案（附全部脚本）：
```sql
set streamName="test_patient_count_update";

load kafka.`` options
`kafka.bootstrap.servers`="dn3:9092"
and `subscribe`="patient"
and `valueFormat`="json"
and `valueSchema`="st(field(name,string),field(age,integer),field(addr,string),field(arriveTime,string))"
as patientKafkaData;

connect jdbc where
url="jdbc:mysql://dn1:3306/streamingpro-cluster?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull"
and driver="com.mysql.jdbc.Driver"
and user="XXX"
and password="XXXXX"
as mydb;

-- set PROCEDURE string 设置存储过程字符串
set procStr='''
CREATE DEFINER=`app`@`%` PROCEDURE `test_proc`(in `dt` date,in `addr` VARCHAR(100),in `num` BIGINT)
begin 
	DECLARE cnt bigint;
	select p.num into cnt from patientUpdate p where p.dt=`dt` and p.addr=`addr`;
	if ISNULL(CNT) then 
		INSERT into patientUpdate(dt,addr,num) values(`dt`,`addr`,`num`);
	else 
		update patientUpdate p set p.num=`num` where p.dt=`dt` and p.addr=`addr`;
	end if;
end
''' ;
-- create table and procedure 创建table和存储过程
select 1 as a as FAKE_TABLE;
run FAKE_TABLE as JDBC.`mydb` where 
`driver-statement-0`="create table  if not exists patientUpdate(dt date,addr varchar(100),num BIGINT)"
and 
`driver-statement-1`="DROP PROCEDURE IF EXISTS test_proc;"
and
`driver-statement-2`="${procStr}"


select name,addr,cast(from_unixtime(arriveTime/1000) as date) as dt from patientKafkaData as patient;

select dt,addr,count(*) as num from patient
group by dt,addr
as groupTable;


save append groupTable
as jdbc.`mydb.patient` 
options mode="update"
-- call procedure 调用存储过程
and `statement-0`="call test_proc(?,?,?)"
and duration="5"
and checkpointLocation="/streamingpro-test/kafka/patient/mysql/update";
```
As you see, I create Mysql Procedure to solve my problem.
如上，我创建了一个mysql的存储过程解决了我的问题。

But, I have no idea the second below is better enough.
但是我不清楚是不是有更好的方案。
So, I create this issue to discuss how to optimize this script.
因此，我创建了这个issue来讨论，如何优化这段脚本，以这个简单的需求为出发点，新来的同学可以参考下写mlsql的大体流程，老手可以教教我们这些萌新。

And I have other confusion about `statement-[num]` , what should I write in `statement-[num]`? Whether the  column name in script should be the same as db's table column name or db's procedure's input param name?
同时，对于 `statement-[num]`我也很困惑。我应该在这里写什么呢？这里要写的是mysql中可执行的语句？因为这里写的语句，value值用问号`?`代替了，是不是说明脚本中的列名要与数据库表中的列名相同才可以？

**Comment by allwefantasy** [comment]
1. You should  upgrade to [v.1.1.7.1](https://www.jianshu.com/p/c0d3f99b1e82) which has been released yesterday since there is a [Issue-906](https://github.com/allwefantasy/streamingpro/issues/906) in preview version.

2. `statement-[number]`  only supports `?` parameter which means it set the parameters by position not by name.

For example:

```sql
select a, b,c d from table1 as table2;

save append table2
as jdbc.`mydb.patient` 
options mode="update"
and `statement-0`="insert patient(jack) values(?)"
....
```
In this code snippet,  column `a` in table2 will be set to jack column in patient table .

3. The better way to avoid calling `PROCEDURE` is use  the `ON DUPLICATE KEY UPDATE` in MySQL

For example:

```sql
insert into patient (a,b,c) values (?,?,?)
ON DUPLICATE KEY UPDATE
(a,b)
```
You can use it like this in MLSQL:

```sql
save append table2
as jdbc.`mydb.patient` 
options mode="update"
and `statement-0`=''''
      insert into patient (a,b,c) values (?,?,?) 
     ON DUPLICATE KEY UPDATE
     (a,b)
''';
```

Notice that we can use `'''` to wrap text.

**Comment by zml1206** [comment]
You can use it like this:
`statement-0`="replace into test1(dt,addr,num) values(?,?,?)";
Mysql "replace into" is an enhanced version of "Insert into".
"Replace into" First try to insert data into the table.
1. If you find that the row already has data in the table (based on the primary key or unique index), delete the row data first, then insert the new data. 
2. Otherwise, insert new data directly.

**Comment by 935205406** [comment]
> 1. You should  upgrade to [v.1.1.7.1](https://www.jianshu.com/p/c0d3f99b1e82) which has been released yesterday since there is a [Issue-906](https://github.com/allwefantasy/streamingpro/issues/906) in preview version.
> 2. `statement-[number]`  only supports `?` parameter which means it set the parameters by position not by name.
> 
> For example:
> 
> ```sql
> select a, b,c d from table1 as table2;
> 
> save append table2
> as jdbc.`mydb.patient` 
> options mode="update"
> and `statement-0`="insert patient(jack) values(?)"
> ....
> ```
> 
> In this code snippet, column `a` in table2 will be set to jack column in patient table .
> 
> 1. The better way to avoid calling `PROCEDURE` is use  the `ON DUPLICATE KEY UPDATE` in MySQL
> 
> For example:
> 
> ```sql
> insert into patient (a,b,c) values (?,?,?)
> ON DUPLICATE KEY UPDATE
> (a,b)
> ```
> 
> You can use it like this in MLSQL:
> 
> ```sql
> save append table2
> as jdbc.`mydb.patient` 
> options mode="update"
> and `statement-0`=''''
>       insert into patient (a,b,c) values (?,?,?) 
>      ON DUPLICATE KEY UPDATE
>      (a,b)
> ''';
> ```
> 
> Notice that we can use `'''` to wrap text.

I use the `ON DUPLICATE KEY UPDATE` like below:

```sql
save append groupTable  
as jdbc.`mydb.patient` 
options mode="update"
and `statement-0`="insert into patientUpdate(dt,addr,num) value(?,?,?) ON DUPLICATE KEY UPDATE dt=?,addr=?,num=?;"
and duration="5"
and checkpointLocation="/streamingpro-test/kafka/patient/mysql/update";
```

and it occurred the below error:

```
[2019-01-18 15:36:08,831][ERROR][org.apache.spark.sql.execution.streaming.MicroBatchExecution] Query test_new_statement [id = 9ac8c6a2-c713-48e8-ab18-378de13fe606, runId = 3d46e0f4-761a-44bc-91c3-6e275efc2584] terminated with error
org.apache.spark.SparkException: Job aborted due to stage failure: Task 66 in stage 1.0 failed 4 times, most recent failure: Lost task 66.3 in stage 1.0 (TID 92, dn3, executor 1): java.lang.ArrayIndexOutOfBoundsException: 3
	at org.apache.spark.sql.execution.streaming.JDBCSink$$anon$1$$anonfun$executeUpdate$1.apply$mcVI$sp(jdbc.scala:94)

```

I think this log indicate the last three `?` in `ON DUPLICATE KEY UPDATE dt=?,addr=?,num=?` are out of the param list's bound which is 3.

More log include before and after the error info are here:
链接：https://pan.baidu.com/s/1Z_EtrDKCvNmn1QaFftjKVQ 密码：uldk

How about use position reference instead of  `?`. Like this:
```sql
save append groupTable  
as jdbc.`mydb.patient` 
options mode="update"
and `statement-0`="insert into patientUpdate(dt,addr,num) value(`1`,`2`,`3`) ON DUPLICATE KEY UPDATE dt=`1`,addr=`2`,num=`3`;"
and duration="5"
and checkpointLocation="/streamingpro-test/kafka/patient/mysql/update";
```
Thus, users can specify which value should be used,and can use many times.

**Comment by 935205406** [comment]
> You can use it like this:
> `statement-0`="replace into test1(dt,addr,num) values(?,?,?)";
> Mysql "replace into" is an enhanced version of "Insert into".
> "Replace into" First try to insert data into the table.
> 
> 1. If you find that the row already has data in the table (based on the primary key or unique index), delete the row data first, then insert the new data.
> 2. Otherwise, insert new data directly.

In this way. It really works. But,when I have the old result, the new result will delete first , then insert new result into table.
 I prefer use `update` instead of `delete-insert`, this is because, in my opinion, `delete`  frequently will have effect on DB.
Anyway, Thanks for your reply. I get `replace into` at least. :)

**Comment by allwefantasy** [comment]
>save append groupTable  
as jdbc.`mydb.patient` 
options mode="update"
and `statement-0`="insert into patientUpdate(dt,addr,num) value(`1`,`2`,`3`) ON DUPLICATE KEY UPDATE dt=`1`,addr=`2`,num=`3`;"
and duration="5"
and checkpointLocation="/streamingpro-test/kafka/patient/mysql/update";

This design sees to be nice, but we should not change the original sql hence this will introduce more 
concepts for end users.  

You can walk around this problem by this way:

```sql
select dt,addr,num, dt as dt1, addr as addr2 from groupTable as outputTable;
save append outputTable  
as jdbc.`mydb.patient` 
options mode="update"
and `statement-0`="insert into patientUpdate(dt,addr,num) value(?,?,?) ON DUPLICATE KEY UPDATE dt=?,addr=?,num=?;"
and duration="5"
and checkpointLocation="/streamingpro-test/kafka/patient/mysql/update";
```

You can use select to make your result table more suitable for final insert statement.

**Comment by 935205406** [comment]
> You can use select to make your result table more suitable for final insert statement.

一语惊醒梦中人！ 翻译不了了，语文不好，只能`卧槽`。还要多多学习，动脑子（笑哭）
