### ISSUE TITLE
你好，有没有运维相关的文档

### ISSUE THREAD

**Issue by gsgsdtc** [byzer-org/byzer-lang#92]
你好！
看到这个开源项目很不错，想进一步了解一些信息，不能能否解答一下

1.  有没有一些处理的metrics信息，例如目前处理kafka的处理延时，处理多少消息之类的。
2. 日志需要如何比较方便的查看，问题查找的大致路径是什么
3. 如何比较方便的进行开发调试

感谢！！

**Comment by allwefantasy** [comment]
1. 那个只能在spark ui上看。
2. 日志的话就是标准的spark程序日志
3. 你可以通过IDE启动，你会看到很多以Local开头的类，是可以直接运行的。

**Comment by allwefantasy** [comment]
更多信息还是查看README哦
