### ISSUE TITLE
Rest Api Partially Available. Can't set owner & jobName attribute.

### ISSUE THREAD

**Issue by 935205406** [byzer-org/byzer-lang#920]
I refer to the below docs:
[doc1](https://github.com/allwefantasy/streamingpro/blob/master/docs/en/mlsql-stream.md),  [doc2](http://docs.mlsql.tech/v1.1.7/zh/multi_tenement/conf.html)
I try to submit stream job through Rest Api.
I start MLSQL through below script:
```
$SPARK_HOME/bin/spark-submit --class streaming.core.StreamingApp \
        --jars ${JARS} \
        --master yarn-client \
        --name mlsqlMyTest \
        --conf "spark.sql.hive.thriftServer.singleSession=true" \
        --conf "spark.kryoserializer.buffer=256k" \
        --conf "spark.kryoserializer.buffer.max=1024m" \
        --conf "spark.serializer=org.apache.spark.serializer.KryoSerializer" \
        --conf "spark.scheduler.mode=FAIR" \
        ${MLSQL_HOME}/libs/${MAIN_JAR}    \
        -streaming.name mlsqlOwnUse    \
        -streaming.platform spark   \
        -streaming.rest true   \
        -streaming.driver.port 9003   \
        -streaming.spark.service true \
        -streaming.thrift false \
        -streaming.enableHiveSupport true \
        -streaming.udf.clazznames streaming.crawler.udf.Functions

```
I can run script and kill job by groupId, but the problem is I can't set `owner` attribute.

I use java to build a project.And use `HttpComponentsClientHttpRequestFactory` to create Spring's RestTemplate:
```java
@Configuration
public class SSRestTemplateConfig {

    @Bean
    public RestTemplate restTemplate(ClientHttpRequestFactory factory){
        return new RestTemplate(factory);
    }

    @Bean
    public ClientHttpRequestFactory simpleClientHttpRequestFactory(){
        //使用 http-client 的 factory 时因为这个可以使用 patch
        HttpComponentsClientHttpRequestFactory factory = new HttpComponentsClientHttpRequestFactory();
        //SimpleClientHttpRequestFactory factory = new SimpleClientHttpRequestFactory();
        factory.setConnectTimeout(15000);
        factory.setReadTimeout(5000);
        return factory;
    }
}
```

Then , in my Controller, I receive script, owner, jobName info. And post them by restTemplate:
```java
HttpHeaders headers = new HttpHeaders();
headers.add("Content-Type", "application/x-www-form-urlencoded");
headers.add("X-Requested-With", "XMLHttpRequest");
headers.add("Accept", "*/*");
//参数
MultiValueMap<String, Object> param = new LinkedMultiValueMap<String, Object>();
param.add("sql", jobSubmitRequest.getScript());
param.add("owner",jobSubmitRequest.getUser());
param.add("jobName",jobSubmitRequest.getJobName());
param.add("silence",true);//返回结果
HttpEntity<MultiValueMap<String, Object>> formEntity = new  HttpEntity<MultiValueMap<String, Object>>(param, headers);
ResponseEntity<String> res = restTemplate.postForEntity(submitUrl, formEntity, String.class);
```

I can submit the script and run successfully, just like submit in MLSQL default console. However, I also set 
`owner` and `jobName`  which are not effective.
I also use `headers.add("Content-Type", "application/json);`, but return `500 Server Error`
And I try to set param in request uri instead of request body, still can run the script while can't set `owner` and `jobName` attribute.

I wonder whether the method I used in my java application is incorrect or some other reasons.

Can Anyone post script and set owner and jobName through MLSQL REST API? 

And if it is possible return the groupId when I post script? So,I can store the groupId and check the job status periodiclly

**Comment by allwefantasy** [comment]
Can you tell that how do you make sure that owner and jobName are not work?

**Comment by allwefantasy** [comment]
Stream job for now ,it is not managed by MLSQL, so wen you use 

```
load _mlsql_.`jobs` as output;
```
the stream job will not show .

For now ,you can use `/stream/jobs/running` to get the jobid, but the owner and other filed are null.

This means there are no problems about your code. 😁

So the best  way to check the stream job status  periodiclly is remember your jobName(for example: my-first-stream-job), and then visit the API

```
http://127.0.0.1:9003/stream/jobs/running
```

and filter the item whose  jobName is equal to "my-first-stream-job" then get the groupId, so you can kill it if need.

Hope this helps.

**Comment by allwefantasy** [comment]
Also we will improve the stream job management  in MLSQL 1.2.0.

**Comment by allwefantasy** [comment]
We have fixed this issue in PR-924. We will close this issue, if there are any problems, please reopen it or create a new issue.
