### ISSUE TITLE
Save JDBC format will not work when set driver-statement and statement at the same time

### ISSUE THREAD

**Issue by 935205406** [byzer-org/byzer-lang#921]
In the below issue. 
#906 
I follow the [doc](http://docs.mlsql.tech/zh/stream/datasource.html).And I can create talbe but can't insert into table.
When I modify save statement as below, it works:
```sql
-- save the data to mysql.
save append table21  
as jdbc.`mysql1.test1` 
options mode="Complete"
and `driver-statement-0`="create table  if not exists test1(k TEXT,c BIGINT)"
-- modify 0 to 1
and `statement-1`="insert into wow.test1(k,c) values(?,?)"
and duration="3"
and checkpointLocation="/tmp/cpl3";
```
I modify `statement-0` to `statement-1`.

Whether should fix the doc or fix it as it is a bug?

**Comment by allwefantasy** [comment]
v1.1.7.1 should have fixed this issue. What is your version?

**Comment by allwefantasy** [comment]
I have checked the code and only v1.1.7.1 on spark 2.3 have been fixed.
We will fix all spark version in release 1.2.0

**Comment by allwefantasy** [comment]
This issue is related to #906 . and we have fixed it in [PR-923](https://github.com/allwefantasy/streamingpro/pull/923)

**Comment by allwefantasy** [comment]
We will close this issue. If needs, you can reopen it or create a new issue.
