### ISSUE TITLE
Failed to find data source: csvStr.

### ISSUE THREAD

**Issue by hanyou** [byzer-org/byzer-lang#940]
1.1.7， spark2.4
执行：
set rawData='''
name,age
zhangsan,1
lisi,2
''';

load csvStr.`rawData` options header="true"
as output;

结果：
Failed to find data source: csvStr. Please find packages at http://spark.apache.org/third-party-projects.html

**Comment by allwefantasy** [comment]
csvStr only support in the master branch. It should be released in MLSQL 1.2.0
