### ISSUE TITLE
How to integrate H2O and Keras

### ISSUE THREAD

**Issue by hanyou** [byzer-org/byzer-lang#942]
如果使用H2O和Keras进行建模，建模后的模型如何在MLSQL中执行预测？

**Comment by allwefantasy** [comment]
For now, MLSQL requires that the training stage is done by MLSQL Platform too. 
Please refer this [doc](http://docs.mlsql.tech/v1.1.7.1/zh/python_alg/sklearn.html). 

Also, MLSQL have already integrated [BigDL](https://github.com/intel-analytics/BigDL) which provide the Keras style API, check the [dl-doc](http://docs.mlsql.tech/v1.1.7.1/zh/dl/)

**Comment by hanyou** [comment]
如果我自己写一个h2o的ET的模块是否可行？编写的标准和规范是什么，是否有文档？
