### ISSUE TITLE
How to secure your Rest API In MLSQL(如果对Rest API进行保护)

### ISSUE THREAD

**Issue by hanyou** [byzer-org/byzer-lang#945]
For now, MLSQL Rest APIs have no authentication, the user can do anything with accessing endpoint /run/script. If deployed in production, it has a risk. How to protect the API?

现在所有的API都是开放的，像/run/script可在远程做任何事情，如果正式部署在生产环境下是比较危险的，如果对API进行保护？

**Comment by allwefantasy** [comment]
This is a good question. We have no auth in MLSQL so you should place it in a secure place(for example, intranet), then you can provide a proxy(e.g. Nginx or application you develop) which have a  auth mechanism to serve.

**Comment by allwefantasy** [comment]
However, MLSQL has done a lot of work on how to control the data source access.  Check this [topic](http://docs.mlsql.tech/zh/security/)
