### ISSUE TITLE
How to protect scripts, models?

### ISSUE THREAD

**Issue by hanyou** [byzer-org/byzer-lang#949]
We train the model in our own company and then deploy it to the client company. How does MLSQL protect the scripts and models from being seen?
我们在自己公司进行模型的训练，然后到客户公司进行部署，MLSQL如何保护脚本和模型不被人看到？

**Comment by allwefantasy** [comment]
MLSQL is just a compute engine for executing MLSQL script and it does not save the script and model. The script should be saved and managed by a web system, and the model should be placed in secure HDFS. 

Please make sure MLSQL compute engine in a intranet and cannot be accessed by the internet as we discussed in [pre-issue](https://github.com/allwefantasy/streamingpro/issues/945)

We have developed a [system ](https://www.jianshu.com/p/3bb7ac280f93) to do these stuff and we hope we can speed the development progress.
