### ISSUE TITLE
How to write file by day in stream mode.

### ISSUE THREAD

**Issue by 935205406** [byzer-org/byzer-lang#950]
I load date from kafka . And process them then write to hdfs which split by day. This is my script:
我有一个流式sql，从kafka加载数据，经过处理后，按天写入hdfs，下面是我的sql
```
-- load from kafka
load kafka ...
...
as kafkaTable;

-- process
select * from kafkaTable as resTable

-- set day directory
set dayDir=`day=${date.toString("yyyyMMdd")}`;

-- save to hdfs
save append resTable
as json.`/path/to/${dayDir}`
and duration="10"
and fileNum="1"
and checkpointLocation="/path/to/checkpoint";

```

In order to test rolling file by time. I modify `set dayDir` as 
为了测试是否能按天滚动，我修改了 `set dayDir` ：
```
set dayDir=`day=${date.toString("yyyyMMdd-HHmm")}`;
```

And I expect write data to different dir in different minites. However all file are in the same dir - which the dir was created when the stream job started, and no new dir created as time goes.
当我运行脚本时，我期望的是在不同的分钟内，数据能写入不同的文件夹。但是所有的文件都写入了同一个文件夹，这个文件夹只在job被启动时创建，随着时间的推移，不会有新的文件夹创建。

So HOW TO WRITE DATA TO DIFFERENT DIRECTORY BY TIME?
请问，该如何修改才可以做到文件按天滚动写入hdfs呢？

MLSQL VERSION:1.1.7.1

**Comment by allwefantasy** [comment]
Try this:

```sql
-- Suppose you have format the created_at
selecte created_at  from .....
-- Then try to save with created_at as the partition columns.
save append resTable
as json.`/path/to/${dayDir}`
and duration="10"
and fileNum="1"
and checkpointLocation="/path/to/checkpoint"
partitionBy created_at
;
```

This is called a dynamic partition and is build-in support.
