### ISSUE TITLE
Invalid TransmogrifAI license

### ISSUE THREAD

**Issue by tovbinm** [byzer-org/byzer-lang#956]
Hello,

We have noticed that your project uses TransmogrifAI code but has [invalid license on it](https://github.com/allwefantasy/streamingpro/blob/fe77b7ffa511928e17ad7c1f38d17d64a9823e23/contri/streamingpro-automl/src/main/java/com/salesforce/op/WowOpWorkflow.scala) (Apache 2.0).

TransmogrifAI is open sourced under [BSD-3 license](https://github.com/salesforce/TransmogrifAI/blob/master/LICENSE) so please keep the original license header.

Thank you.

**Comment by allwefantasy** [comment]
OK  i will fix this as soon as possible

**Comment by allwefantasy** [comment]
@tovbinm  I have created a new [PR](https://github.com/allwefantasy/streamingpro/pull/958)  to fix this issue. Can you review it and check is there something else I have missed?

**Comment by tovbinm** [comment]
Thanks. LGTM.
