### ISSUE TITLE
presto-jdbc  Unrecognized connection property '_filePath_'

### ISSUE THREAD

**Issue by motto1314** [byzer-org/byzer-lang#959]
你好：
问题如下。

1、添加了presto-jdbc驱动jar包到libs目录
2、  connect jdbc where
 url="jdbc:presto://127.0.0.1:9099/hive/dw"
 and driver="com.facebook.presto.jdbc.PrestoDriver"
 and user="root"
 and password=""
 as db_3;
 
 
 load jdbc.`db_3.test1` as table5;

运行时报错：
Unrecognized connection property '_filePath_'

**Comment by allwefantasy** [comment]
Can you try the master branch?  You can build the project by this [tutorial](http://docs.mlsql.tech/zh/installation/compile.html)
