### ISSUE TITLE
List Running Jobs failed when a job with wrong kafka conf submit.

### ISSUE THREAD

**Issue by 935205406** [byzer-org/byzer-lang#988]
First. I submit a stream job , and I can see it in '任务列表'.
首先启动一个含有kafka source的任务，启动后，可以在 ‘任务列表’ 中看到它已经启动。

Then, I modify the job's name(by `set streamName` keyword) and modify the `checkpointLocation` conf. And the most important operator is : I modify kafka's `kafka.bootstrap.servers` to be a wrong ip address.
然后，我修改了任务名（通过 `set streamName` 关键字），修改了 `checkpointLocation` 配置，这样就可以再次提交这个进行了微小变化的任务，而不会报任务名重复或从checkpointLocation重启的错误。然后关键的一步是：我将kafka source中的 `kafka.bootstrap.servers` 故意设置为一个错误的地址，以模拟使用mlsql时，可能出现的问题。

And I submit the job.
然后，我提交了这个修改后的任务。

The result is that, in '任务列表' page, I can't see the second job, and I can't see the first success job as well! Though, I can see the two job are all submited to Spark's by Spark UI http://sparkip:port/SQL/ . And when the kafka has records,the first success submited job which can't see in '任务列表' are still working , I can see this by Spark UI http://sparkip:port/jobs
结果是，在‘任务列表’页面，我没有看到第二次提交的任务，同时，第一次提交的正确配置的任务也看不到了。但是，我通过SPARK UI 的 http://sparkip:port/SQL/ ，可以看到两个任务都已经提交了，执行了createOrReplaceTempView。并且，若kafka有数据，第一次提交的任务（现在已经在‘任务列表’看不到其正在运行）仍然可以处理数据，可以通过SPARK UI 的 http://sparkip:port/jobs 看到处理过程。

When I get running job on the other way : http restful api.  `GET http://ip:port/stream/jobs/running` with`Content-Type:application/json`  .The result is a http page say 
```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1">
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /stream/jobs/running. Reason:
<pre>    java.lang.NullPointerException</pre></p>
<hr ><i><small>Powered by Jetty://</small></i>
</body>
</html>
```
当我使用另一种方式 http restful api 来获取running jobs时，使用的命令为  `GET http://ip:port/stream/jobs/running`  以及 `Content-Type:application/json`，返回的是一个http页面（正确的情况下应该为job信息的json数据）

The mlsql did not print any error info on console.
整个过程中，mlsql没有在控制台打印任何错误信息。

**Comment by allwefantasy** [comment]
In MLSQL, you can run a script like this to list all jobs(batch/stream):

```
load _mlsql_.`jobs` as output;
```
